// Code generated by contract/gen_go.go from contract/schemas; DO NOT EDIT.
//
// Single-source WS contract for v2: wire names keep v1 continuity,
// v2 session FrameKind -> wire name mapping is FrameKindToWireName.
// Regenerate both mirrors with: go generate ./contract (requires Node.js).

package wscontract

import (
	"encoding/json"
	"fmt"
	"math"
	"time"
)

type AssistantDelta struct {
	Content      *string         `json:"content,omitempty"`
	ContentIndex *int64          `json:"contentIndex,omitempty"`
	Delta        *string         `json:"delta,omitempty"`
	Kind         string          `json:"kind"`
	Partial      json.RawMessage `json:"partial,omitempty"`
	Reason       *string         `json:"reason,omitempty"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type AssistantMessage struct {
	Blocks     []ContentBlock  `json:"blocks,omitempty"`
	Content    *string         `json:"content,omitempty"`
	CustomType *string         `json:"customType,omitempty"`
	Model      *string         `json:"model,omitempty"`
	Role       string          `json:"role"`
	Timestamp  *float64        `json:"timestamp,omitempty"`
	Ts         *float64        `json:"ts,omitempty"`
	Usage      json.RawMessage `json:"usage,omitempty"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ChatImage struct {
	Data     string `json:"data"`
	MimeType string `json:"mimeType"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type CommandEntry struct {
	Description *string            `json:"description,omitempty"`
	Name        string             `json:"name"`
	Source      *string            `json:"source,omitempty"`
	SourceInfo  *CommandSourceInfo `json:"sourceInfo,omitempty"`
	Syntax      *string            `json:"syntax,omitempty"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type CommandSourceInfo struct {
	BaseDir *string `json:"baseDir,omitempty"`
	Origin  *string `json:"origin,omitempty"`
	Path    *string `json:"path,omitempty"`
	Scope   *string `json:"scope,omitempty"`
	Source  *string `json:"source,omitempty"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ContentBlock struct {
	Arguments json.RawMessage `json:"arguments,omitempty"`
	ID        *string         `json:"id,omitempty"`
	IsError   *bool           `json:"isError,omitempty"`
	Kind      string          `json:"kind"`
	Name      *string         `json:"name,omitempty"`
	Text      *string         `json:"text,omitempty"`
	Thinking  *string         `json:"thinking,omitempty"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ContextUsage struct {
	ContextWindow *int64  `json:"contextWindow,omitempty"`
	Percent       float64 `json:"percent"`
	Tokens        *int64  `json:"tokens,omitempty"`
	Total         *int64  `json:"total,omitempty"`
	Used          *int64  `json:"used,omitempty"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ModelInfo struct {
	Input    []string `json:"input,omitempty"`
	ModelID  string   `json:"modelId"`
	Name     *string  `json:"name,omitempty"`
	Provider string   `json:"provider"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ModelRef struct {
	ModelID  string `json:"modelId"`
	Provider string `json:"provider"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ResumeCandidate struct {
	HostPath *string `json:"hostPath,omitempty"`
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type TokenUsage struct {
	CacheRead  *int64 `json:"cacheRead,omitempty"`
	CacheWrite *int64 `json:"cacheWrite,omitempty"`
	Input      *int64 `json:"input,omitempty"`
	Output     *int64 `json:"output,omitempty"`
	Total      *int64 `json:"total,omitempty"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ToolPayloadContentItem struct {
	Text *string `json:"text,omitempty"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ToolPayload struct {
	Content []ToolPayloadContentItem `json:"content,omitempty"`
	Details json.RawMessage          `json:"details,omitempty"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ClientHelloFrame struct {
	Type string `json:"type"`
	// Wire contract version the client expects
	Version int64 `json:"version"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type HelloFrame struct {
	// Human-readable server build identity
	ServerVersion string `json:"serverVersion"`
	Type          string `json:"type"`
	// Wire contract version this server speaks
	Version int64 `json:"version"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type AckFrame struct {
	Command string  `json:"command"`
	ID      *string `json:"id,omitempty"`
	// Correlates with the client request (invariant 19)
	RequestID *string `json:"requestId,omitempty"`
	SessionID *string `json:"sessionId,omitempty"`
	Type      string  `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ActivitySnapshot struct {
	Data      json.RawMessage `json:"data,omitempty"`
	Name      string          `json:"name"`
	Oversized bool            `json:"oversized"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ApprovalFrame struct {
	ID          string         `json:"id"`
	Message     *string        `json:"message,omitempty"`
	Method      ApprovalMethod `json:"method"`
	Options     []string       `json:"options,omitempty"`
	Placeholder *string        `json:"placeholder,omitempty"`
	Prefill     *string        `json:"prefill,omitempty"`
	SessionID   string         `json:"sessionId"`
	Timeout     *int64         `json:"timeout,omitempty"`
	Title       *string        `json:"title,omitempty"`
	Type        string         `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ChatNameFrame struct {
	Name      string     `json:"name"`
	Origin    NameOrigin `json:"origin"`
	SessionID string     `json:"sessionId"`
	Type      string     `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type CommandsFrame struct {
	Commands  []CommandEntry `json:"commands"`
	SessionID string         `json:"sessionId"`
	Type      string         `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type CompactionDoneFrame struct {
	Error     *string `json:"error,omitempty"`
	SessionID string  `json:"sessionId"`
	Type      string  `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type CompactionStartedFrame struct {
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ControlResultFrame struct {
	Command   string  `json:"command"`
	Message   *string `json:"message,omitempty"`
	RequestID *string `json:"requestId,omitempty"`
	SessionID string  `json:"sessionId"`
	Success   bool    `json:"success"`
	Type      string  `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type DagDigest struct {
	ReceivedAt *string          `json:"received_at,omitempty"`
	Runs       []RunDigestEntry `json:"runs"`
	Truncated  bool             `json:"truncated"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type EntriesFrame struct {
	// History entries; bounds per invariant 18 (100 entries / 256 KiB per page)
	Entries []json.RawMessage `json:"entries"`
	// REQUIRED on every entries frame (invariant 18)
	Final bool `json:"final"`
	// Present only on the terminal page
	LeafID    *string `json:"leafId,omitempty"`
	SessionID string  `json:"sessionId"`
	Type      string  `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ErrorFrame struct {
	// resume_failed only: scanned branch candidates
	Candidates []ResumeCandidate `json:"candidates,omitempty"`
	Code       *ErrorCode        `json:"code,omitempty"`
	// FailedRpcCommand — provider command string, open on purpose
	Command *string `json:"command,omitempty"`
	// resume_failed only: stored identity path no longer exists
	Dangling *bool `json:"dangling,omitempty"`
	// external-write-detected only: daemon session leaf
	KnownLeaf *string `json:"knownLeaf,omitempty"`
	Message   string  `json:"message"`
	// external-write-detected only: disk session leaf
	ObservedLeaf *string `json:"observedLeaf,omitempty"`
	RequestID    *string `json:"requestId,omitempty"`
	SessionID    *string `json:"sessionId,omitempty"`
	Type         string  `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ExtensionEventFrame struct {
	Data      json.RawMessage `json:"data,omitempty"`
	Name      string          `json:"name"`
	SessionID string          `json:"sessionId"`
	Type      string          `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type MessageDeltaFrame struct {
	Delta     AssistantDelta `json:"delta"`
	MessageID *string        `json:"messageId,omitempty"`
	SessionID string         `json:"sessionId"`
	Type      string         `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type MessageFrame struct {
	Message   AssistantMessage `json:"message"`
	SessionID string           `json:"sessionId"`
	Type      string           `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ModelsFrame struct {
	Models    []ModelInfo `json:"models"`
	SessionID string      `json:"sessionId"`
	Type      string      `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type NoticeFrame struct {
	// RFC3339Nano receipt time; every notice carries one (invariant 14)
	At string `json:"at"`
	// Open set: durable kinds are enumerated in notice-kinds.json; everything else is transient
	Kind string `json:"kind"`
	// Server-assigned replay identity for durable notices
	Nid       *string         `json:"nid,omitempty"`
	Payload   json.RawMessage `json:"payload,omitempty"`
	SessionID string          `json:"sessionId"`
	Type      string          `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type PongFrame struct {
	SessionID *string `json:"sessionId,omitempty"`
	Type      string  `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ReadyFrame struct {
	PISessionID *string `json:"piSessionId"`
	Resumed     bool    `json:"resumed"`
	SessionID   string  `json:"sessionId"`
	Type        string  `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type RunDigestEntry struct {
	RunID          string   `json:"run_id"`
	RunningTaskIds []string `json:"running_task_ids"`
	Status         string   `json:"status"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type RunDoneFrame struct {
	Reason    string `json:"reason"`
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type RunStartedFrame struct {
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// SessionsActivityFrame — Latest overview activity for one subscribed session. durableSessionId is the provider-stable identity; replacesSessionId names a provisional row that sessionId replaces. snapshots are ordered task then DAG; overflow reports that this socket dropped older activity frames.
type SessionsActivityFrame struct {
	DagDigest         *DagDigest         `json:"dagDigest,omitempty"`
	DurableSessionID  string             `json:"durableSessionId"`
	Overflow          bool               `json:"overflow"`
	ReplacesSessionID *string            `json:"replacesSessionId,omitempty"`
	SessionID         string             `json:"sessionId"`
	Snapshots         []ActivitySnapshot `json:"snapshots"`
	TaskDigest        *TaskDigest        `json:"taskDigest,omitempty"`
	Type              string             `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type StateFrame struct {
	IsCompacting  bool      `json:"isCompacting"`
	IsStreaming   bool      `json:"isStreaming"`
	Model         *ModelRef `json:"model,omitempty"`
	SessionID     string    `json:"sessionId"`
	SessionName   *string   `json:"sessionName,omitempty"`
	ThinkingLevel *string   `json:"thinkingLevel,omitempty"`
	Type          string    `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type StatsFrame struct {
	ContextUsage *ContextUsage `json:"contextUsage,omitempty"`
	Cost         *float64      `json:"cost,omitempty"`
	SessionID    string        `json:"sessionId"`
	Tokens       *TokenUsage   `json:"tokens,omitempty"`
	Type         string        `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type TaskDigest struct {
	ReceivedAt *string           `json:"received_at,omitempty"`
	Tasks      []TaskDigestEntry `json:"tasks"`
	Truncated  bool              `json:"truncated"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type TaskDigestEntry struct {
	Status    string  `json:"status"`
	TaskID    string  `json:"task_id"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ToolFrame struct {
	Args       json.RawMessage `json:"args,omitempty"`
	IsError    *bool           `json:"isError,omitempty"`
	Partial    *ToolPayload    `json:"partial,omitempty"`
	Phase      ToolPhase       `json:"phase"`
	Result     *ToolPayload    `json:"result,omitempty"`
	SessionID  string          `json:"sessionId"`
	ToolCallID string          `json:"toolCallId"`
	ToolName   string          `json:"toolName"`
	Type       string          `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ActivityRefreshFrame struct {
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ApprovalRespondFrame struct {
	Cancelled *bool   `json:"cancelled,omitempty"`
	Confirmed *bool   `json:"confirmed,omitempty"`
	ID        string  `json:"id"`
	RequestID *string `json:"requestId,omitempty"`
	SessionID string  `json:"sessionId"`
	Type      string  `json:"type"`
	Value     *string `json:"value,omitempty"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ChatAbortFrame struct {
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ChatCloseFrame struct {
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ChatCommandsFrame struct {
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ChatCompactFrame struct {
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ChatCreateFrame struct {
	ChatID string `json:"chatId"`
	// Explicitly authorizes replacement of a quarantined in-place provider route
	Recovery *bool  `json:"recovery,omitempty"`
	Type     string `json:"type"`
	WsID     string `json:"wsId"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ChatDisconnectFrame struct {
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ChatModelsFrame struct {
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ChatResumeFrame struct {
	SessionID string  `json:"sessionId"`
	Since     *string `json:"since,omitempty"`
	Type      string  `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ChatSendFrameRun struct {
	Images  []ChatImage `json:"images,omitempty"`
	Kind    RunKind     `json:"kind"`
	Message string      `json:"message"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ChatSendFrame struct {
	Run       ChatSendFrameRun `json:"run"`
	SessionID string           `json:"sessionId"`
	Type      string           `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ChatSetFrame struct {
	Model         *ModelRef `json:"model,omitempty"`
	RequestID     *string   `json:"requestId,omitempty"`
	SessionID     string    `json:"sessionId"`
	ThinkingLevel *string   `json:"thinkingLevel,omitempty"`
	Type          string    `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type ChatStatsFrame struct {
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

type PingFrame struct {
	Type string `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// SessionsSubscribeFrame — Replaces this socket's activity subscription. all_live follows every live overview row; explicit follows sessionIds; none unsubscribes.
type SessionsSubscribeFrame struct {
	Mode       string   `json:"mode"`
	SessionIds []string `json:"sessionIds,omitempty"`
	Type       string   `json:"type"`
	// ExtraFields preserves unknown properties for forward-compatible round trips.
	ExtraFields map[string]json.RawMessage `json:"-"`
}

// Known frame and nested object decoders retain unknown properties. This is an
// intentional forward-compatibility exception to schema additionalProperties:false.
func captureExtraFields(data []byte, known, preserveNullable, preserveArrays []string) (map[string]json.RawMessage, error) {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return nil, err
	}
	knownSet := make(map[string]bool, len(known))
	for _, key := range known {
		knownSet[key] = true
	}
	preserveNullSet := make(map[string]bool, len(preserveNullable))
	for _, key := range preserveNullable {
		preserveNullSet[key] = true
	}
	preserveArraySet := make(map[string]bool, len(preserveArrays))
	for _, key := range preserveArrays {
		preserveArraySet[key] = true
	}
	for key, raw := range fields {
		if !knownSet[key] {
			continue
		}
		text := string(raw)
		if preserveNullSet[key] && text == "null" {
			continue
		}
		if preserveArraySet[key] && text == "[]" {
			continue
		}
		delete(fields, key)
	}
	if len(fields) == 0 {
		return nil, nil
	}
	return fields, nil
}

func marshalWithExtra(known any, extra map[string]json.RawMessage) ([]byte, error) {
	data, err := json.Marshal(known)
	if err != nil || len(extra) == 0 {
		return data, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return nil, err
	}
	for key, raw := range extra {
		if _, exists := fields[key]; !exists {
			fields[key] = raw
		}
	}
	return json.Marshal(fields)
}

func (v *AssistantDelta) UnmarshalJSON(data []byte) error {
	type plain AssistantDelta
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"content", "contentIndex", "delta", "kind", "partial", "reason"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v AssistantDelta) MarshalJSON() ([]byte, error) {
	type plain AssistantDelta
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *AssistantMessage) UnmarshalJSON(data []byte) error {
	type plain AssistantMessage
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"blocks", "content", "customType", "model", "role", "timestamp", "ts", "usage"}, []string{}, []string{"blocks"})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v AssistantMessage) MarshalJSON() ([]byte, error) {
	type plain AssistantMessage
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ChatImage) UnmarshalJSON(data []byte) error {
	type plain ChatImage
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"data", "mimeType"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ChatImage) MarshalJSON() ([]byte, error) {
	type plain ChatImage
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *CommandEntry) UnmarshalJSON(data []byte) error {
	type plain CommandEntry
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"description", "name", "source", "sourceInfo", "syntax"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v CommandEntry) MarshalJSON() ([]byte, error) {
	type plain CommandEntry
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *CommandSourceInfo) UnmarshalJSON(data []byte) error {
	type plain CommandSourceInfo
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"baseDir", "origin", "path", "scope", "source"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v CommandSourceInfo) MarshalJSON() ([]byte, error) {
	type plain CommandSourceInfo
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ContentBlock) UnmarshalJSON(data []byte) error {
	type plain ContentBlock
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"arguments", "id", "isError", "kind", "name", "text", "thinking"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ContentBlock) MarshalJSON() ([]byte, error) {
	type plain ContentBlock
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ContextUsage) UnmarshalJSON(data []byte) error {
	type plain ContextUsage
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"contextWindow", "percent", "tokens", "total", "used"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ContextUsage) MarshalJSON() ([]byte, error) {
	type plain ContextUsage
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ModelInfo) UnmarshalJSON(data []byte) error {
	type plain ModelInfo
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"input", "modelId", "name", "provider"}, []string{}, []string{"input"})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ModelInfo) MarshalJSON() ([]byte, error) {
	type plain ModelInfo
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ModelRef) UnmarshalJSON(data []byte) error {
	type plain ModelRef
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"modelId", "provider"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ModelRef) MarshalJSON() ([]byte, error) {
	type plain ModelRef
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ResumeCandidate) UnmarshalJSON(data []byte) error {
	type plain ResumeCandidate
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"hostPath", "id", "name"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ResumeCandidate) MarshalJSON() ([]byte, error) {
	type plain ResumeCandidate
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *TokenUsage) UnmarshalJSON(data []byte) error {
	type plain TokenUsage
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"cacheRead", "cacheWrite", "input", "output", "total"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v TokenUsage) MarshalJSON() ([]byte, error) {
	type plain TokenUsage
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ToolPayloadContentItem) UnmarshalJSON(data []byte) error {
	type plain ToolPayloadContentItem
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"text"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ToolPayloadContentItem) MarshalJSON() ([]byte, error) {
	type plain ToolPayloadContentItem
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ToolPayload) UnmarshalJSON(data []byte) error {
	type plain ToolPayload
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"content", "details"}, []string{}, []string{"content"})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ToolPayload) MarshalJSON() ([]byte, error) {
	type plain ToolPayload
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ClientHelloFrame) UnmarshalJSON(data []byte) error {
	type plain ClientHelloFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"type", "version"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ClientHelloFrame) MarshalJSON() ([]byte, error) {
	type plain ClientHelloFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *HelloFrame) UnmarshalJSON(data []byte) error {
	type plain HelloFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"serverVersion", "type", "version"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v HelloFrame) MarshalJSON() ([]byte, error) {
	type plain HelloFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *AckFrame) UnmarshalJSON(data []byte) error {
	type plain AckFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"command", "id", "requestId", "sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v AckFrame) MarshalJSON() ([]byte, error) {
	type plain AckFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ActivitySnapshot) UnmarshalJSON(data []byte) error {
	type plain ActivitySnapshot
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"data", "name", "oversized"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ActivitySnapshot) MarshalJSON() ([]byte, error) {
	type plain ActivitySnapshot
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ApprovalFrame) UnmarshalJSON(data []byte) error {
	type plain ApprovalFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"id", "message", "method", "options", "placeholder", "prefill", "sessionId", "timeout", "title", "type"}, []string{}, []string{"options"})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ApprovalFrame) MarshalJSON() ([]byte, error) {
	type plain ApprovalFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ChatNameFrame) UnmarshalJSON(data []byte) error {
	type plain ChatNameFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"name", "origin", "sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ChatNameFrame) MarshalJSON() ([]byte, error) {
	type plain ChatNameFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *CommandsFrame) UnmarshalJSON(data []byte) error {
	type plain CommandsFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"commands", "sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v CommandsFrame) MarshalJSON() ([]byte, error) {
	type plain CommandsFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *CompactionDoneFrame) UnmarshalJSON(data []byte) error {
	type plain CompactionDoneFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"error", "sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v CompactionDoneFrame) MarshalJSON() ([]byte, error) {
	type plain CompactionDoneFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *CompactionStartedFrame) UnmarshalJSON(data []byte) error {
	type plain CompactionStartedFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v CompactionStartedFrame) MarshalJSON() ([]byte, error) {
	type plain CompactionStartedFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ControlResultFrame) UnmarshalJSON(data []byte) error {
	type plain ControlResultFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"command", "message", "requestId", "sessionId", "success", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ControlResultFrame) MarshalJSON() ([]byte, error) {
	type plain ControlResultFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *DagDigest) UnmarshalJSON(data []byte) error {
	type plain DagDigest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"received_at", "runs", "truncated"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v DagDigest) MarshalJSON() ([]byte, error) {
	type plain DagDigest
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *EntriesFrame) UnmarshalJSON(data []byte) error {
	type plain EntriesFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"entries", "final", "leafId", "sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v EntriesFrame) MarshalJSON() ([]byte, error) {
	type plain EntriesFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ErrorFrame) UnmarshalJSON(data []byte) error {
	type plain ErrorFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"candidates", "code", "command", "dangling", "knownLeaf", "message", "observedLeaf", "requestId", "sessionId", "type"}, []string{}, []string{"candidates"})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ErrorFrame) MarshalJSON() ([]byte, error) {
	type plain ErrorFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ExtensionEventFrame) UnmarshalJSON(data []byte) error {
	type plain ExtensionEventFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"data", "name", "sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ExtensionEventFrame) MarshalJSON() ([]byte, error) {
	type plain ExtensionEventFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *MessageDeltaFrame) UnmarshalJSON(data []byte) error {
	type plain MessageDeltaFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"delta", "messageId", "sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v MessageDeltaFrame) MarshalJSON() ([]byte, error) {
	type plain MessageDeltaFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *MessageFrame) UnmarshalJSON(data []byte) error {
	type plain MessageFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"message", "sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v MessageFrame) MarshalJSON() ([]byte, error) {
	type plain MessageFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ModelsFrame) UnmarshalJSON(data []byte) error {
	type plain ModelsFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"models", "sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ModelsFrame) MarshalJSON() ([]byte, error) {
	type plain ModelsFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *NoticeFrame) UnmarshalJSON(data []byte) error {
	type plain NoticeFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"at", "kind", "nid", "payload", "sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v NoticeFrame) MarshalJSON() ([]byte, error) {
	type plain NoticeFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *PongFrame) UnmarshalJSON(data []byte) error {
	type plain PongFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v PongFrame) MarshalJSON() ([]byte, error) {
	type plain PongFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ReadyFrame) UnmarshalJSON(data []byte) error {
	type plain ReadyFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"piSessionId", "resumed", "sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ReadyFrame) MarshalJSON() ([]byte, error) {
	type plain ReadyFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *RunDigestEntry) UnmarshalJSON(data []byte) error {
	type plain RunDigestEntry
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"run_id", "running_task_ids", "status"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v RunDigestEntry) MarshalJSON() ([]byte, error) {
	type plain RunDigestEntry
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *RunDoneFrame) UnmarshalJSON(data []byte) error {
	type plain RunDoneFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"reason", "sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v RunDoneFrame) MarshalJSON() ([]byte, error) {
	type plain RunDoneFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *RunStartedFrame) UnmarshalJSON(data []byte) error {
	type plain RunStartedFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v RunStartedFrame) MarshalJSON() ([]byte, error) {
	type plain RunStartedFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *SessionsActivityFrame) UnmarshalJSON(data []byte) error {
	type plain SessionsActivityFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"dagDigest", "durableSessionId", "overflow", "replacesSessionId", "sessionId", "snapshots", "taskDigest", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v SessionsActivityFrame) MarshalJSON() ([]byte, error) {
	type plain SessionsActivityFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *StateFrame) UnmarshalJSON(data []byte) error {
	type plain StateFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"isCompacting", "isStreaming", "model", "sessionId", "sessionName", "thinkingLevel", "type"}, []string{"model"}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v StateFrame) MarshalJSON() ([]byte, error) {
	type plain StateFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *StatsFrame) UnmarshalJSON(data []byte) error {
	type plain StatsFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"contextUsage", "cost", "sessionId", "tokens", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v StatsFrame) MarshalJSON() ([]byte, error) {
	type plain StatsFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *TaskDigest) UnmarshalJSON(data []byte) error {
	type plain TaskDigest
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"received_at", "tasks", "truncated"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v TaskDigest) MarshalJSON() ([]byte, error) {
	type plain TaskDigest
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *TaskDigestEntry) UnmarshalJSON(data []byte) error {
	type plain TaskDigestEntry
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"status", "task_id", "updated_at"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v TaskDigestEntry) MarshalJSON() ([]byte, error) {
	type plain TaskDigestEntry
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ToolFrame) UnmarshalJSON(data []byte) error {
	type plain ToolFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"args", "isError", "partial", "phase", "result", "sessionId", "toolCallId", "toolName", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ToolFrame) MarshalJSON() ([]byte, error) {
	type plain ToolFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ActivityRefreshFrame) UnmarshalJSON(data []byte) error {
	type plain ActivityRefreshFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ActivityRefreshFrame) MarshalJSON() ([]byte, error) {
	type plain ActivityRefreshFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ApprovalRespondFrame) UnmarshalJSON(data []byte) error {
	type plain ApprovalRespondFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"cancelled", "confirmed", "id", "requestId", "sessionId", "type", "value"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ApprovalRespondFrame) MarshalJSON() ([]byte, error) {
	type plain ApprovalRespondFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ChatAbortFrame) UnmarshalJSON(data []byte) error {
	type plain ChatAbortFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ChatAbortFrame) MarshalJSON() ([]byte, error) {
	type plain ChatAbortFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ChatCloseFrame) UnmarshalJSON(data []byte) error {
	type plain ChatCloseFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ChatCloseFrame) MarshalJSON() ([]byte, error) {
	type plain ChatCloseFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ChatCommandsFrame) UnmarshalJSON(data []byte) error {
	type plain ChatCommandsFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ChatCommandsFrame) MarshalJSON() ([]byte, error) {
	type plain ChatCommandsFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ChatCompactFrame) UnmarshalJSON(data []byte) error {
	type plain ChatCompactFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ChatCompactFrame) MarshalJSON() ([]byte, error) {
	type plain ChatCompactFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ChatCreateFrame) UnmarshalJSON(data []byte) error {
	type plain ChatCreateFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"chatId", "recovery", "type", "wsId"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ChatCreateFrame) MarshalJSON() ([]byte, error) {
	type plain ChatCreateFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ChatDisconnectFrame) UnmarshalJSON(data []byte) error {
	type plain ChatDisconnectFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ChatDisconnectFrame) MarshalJSON() ([]byte, error) {
	type plain ChatDisconnectFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ChatModelsFrame) UnmarshalJSON(data []byte) error {
	type plain ChatModelsFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ChatModelsFrame) MarshalJSON() ([]byte, error) {
	type plain ChatModelsFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ChatResumeFrame) UnmarshalJSON(data []byte) error {
	type plain ChatResumeFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"sessionId", "since", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ChatResumeFrame) MarshalJSON() ([]byte, error) {
	type plain ChatResumeFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ChatSendFrameRun) UnmarshalJSON(data []byte) error {
	type plain ChatSendFrameRun
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"images", "kind", "message"}, []string{}, []string{"images"})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ChatSendFrameRun) MarshalJSON() ([]byte, error) {
	type plain ChatSendFrameRun
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ChatSendFrame) UnmarshalJSON(data []byte) error {
	type plain ChatSendFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"run", "sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ChatSendFrame) MarshalJSON() ([]byte, error) {
	type plain ChatSendFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ChatSetFrame) UnmarshalJSON(data []byte) error {
	type plain ChatSetFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"model", "requestId", "sessionId", "thinkingLevel", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ChatSetFrame) MarshalJSON() ([]byte, error) {
	type plain ChatSetFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *ChatStatsFrame) UnmarshalJSON(data []byte) error {
	type plain ChatStatsFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"sessionId", "type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v ChatStatsFrame) MarshalJSON() ([]byte, error) {
	type plain ChatStatsFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *PingFrame) UnmarshalJSON(data []byte) error {
	type plain PingFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"type"}, []string{}, []string{})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v PingFrame) MarshalJSON() ([]byte, error) {
	type plain PingFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

func (v *SessionsSubscribeFrame) UnmarshalJSON(data []byte) error {
	type plain SessionsSubscribeFrame
	if err := json.Unmarshal(data, (*plain)(v)); err != nil {
		return err
	}
	extra, err := captureExtraFields(data, []string{"mode", "sessionIds", "type"}, []string{}, []string{"sessionIds"})
	if err != nil {
		return err
	}
	v.ExtraFields = extra
	return nil
}

func (v SessionsSubscribeFrame) MarshalJSON() ([]byte, error) {
	type plain SessionsSubscribeFrame
	return marshalWithExtra(plain(v), v.ExtraFields)
}

type validationSchema struct {
	Type       string
	Format     string
	Const      string
	Enum       []string
	AnyOf      []validationSchema
	Properties map[string]validationSchema
	Required   []string
	Items      *validationSchema
}

func validateFrameJSON(data []byte, spec validationSchema) error {
	var value any
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	return validateValue(value, spec, "frame")
}

func validateValue(value any, spec validationSchema, path string) error {
	if len(spec.AnyOf) > 0 {
		for _, branch := range spec.AnyOf {
			if validateValue(value, branch, path) == nil {
				return nil
			}
		}
		return fmt.Errorf("%s does not match any allowed schema", path)
	}
	if spec.Const != "" {
		if value != spec.Const {
			return fmt.Errorf("%s must equal %q", path, spec.Const)
		}
	}
	if len(spec.Enum) > 0 {
		text, ok := value.(string)
		if !ok {
			return fmt.Errorf("%s must be a string enum", path)
		}
		found := false
		for _, allowed := range spec.Enum {
			if text == allowed {
				found = true
				break
			}
		}
		if !found {
			return fmt.Errorf("%s has invalid enum value %q", path, text)
		}
	}
	switch spec.Type {
	case "":
		return nil
	case "null":
		if value != nil {
			return fmt.Errorf("%s must be null", path)
		}
	case "string":
		text, ok := value.(string)
		if !ok {
			return fmt.Errorf("%s must be a string", path)
		}
		if spec.Format == "rfc3339nano" {
			if _, err := time.Parse(time.RFC3339Nano, text); err != nil {
				return fmt.Errorf("%s must be RFC3339Nano: %w", path, err)
			}
		}
	case "boolean":
		if _, ok := value.(bool); !ok {
			return fmt.Errorf("%s must be a boolean", path)
		}
	case "number":
		if _, ok := value.(float64); !ok {
			return fmt.Errorf("%s must be a number", path)
		}
	case "integer":
		number, ok := value.(float64)
		if !ok || math.Trunc(number) != number {
			return fmt.Errorf("%s must be an integer", path)
		}
	case "array":
		values, ok := value.([]any)
		if !ok {
			return fmt.Errorf("%s must be an array", path)
		}
		if spec.Items != nil {
			for i, item := range values {
				if err := validateValue(item, *spec.Items, fmt.Sprintf("%s[%d]", path, i)); err != nil {
					return err
				}
			}
		}
	case "object":
		object, ok := value.(map[string]any)
		if !ok {
			return fmt.Errorf("%s must be an object", path)
		}
		for _, key := range spec.Required {
			if _, exists := object[key]; !exists {
				return fmt.Errorf("%s.%s is required", path, key)
			}
		}
		for key, child := range spec.Properties {
			if item, exists := object[key]; exists {
				if err := validateValue(item, child, path+"."+key); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

// ServerFrame is implemented by every server->client frame struct.
type ServerFrame interface{ serverFrame() }

// ClientFrame is implemented by every client->server frame struct.
type ClientFrame interface{ clientFrame() }

func (ReadyFrame) serverFrame()             {}
func (ChatNameFrame) serverFrame()          {}
func (MessageDeltaFrame) serverFrame()      {}
func (MessageFrame) serverFrame()           {}
func (ToolFrame) serverFrame()              {}
func (StateFrame) serverFrame()             {}
func (StatsFrame) serverFrame()             {}
func (ExtensionEventFrame) serverFrame()    {}
func (SessionsActivityFrame) serverFrame()  {}
func (ApprovalFrame) serverFrame()          {}
func (CommandsFrame) serverFrame()          {}
func (ModelsFrame) serverFrame()            {}
func (EntriesFrame) serverFrame()           {}
func (CompactionStartedFrame) serverFrame() {}
func (CompactionDoneFrame) serverFrame()    {}
func (RunStartedFrame) serverFrame()        {}
func (RunDoneFrame) serverFrame()           {}
func (AckFrame) serverFrame()               {}
func (ControlResultFrame) serverFrame()     {}
func (ErrorFrame) serverFrame()             {}
func (NoticeFrame) serverFrame()            {}
func (PongFrame) serverFrame()              {}
func (HelloFrame) serverFrame()             {}
func (u UnknownFrame) serverFrame()         {}

func (PingFrame) clientFrame()              {}
func (ChatCreateFrame) clientFrame()        {}
func (ChatSendFrame) clientFrame()          {}
func (ChatAbortFrame) clientFrame()         {}
func (ChatSetFrame) clientFrame()           {}
func (ApprovalRespondFrame) clientFrame()   {}
func (ChatCommandsFrame) clientFrame()      {}
func (ChatCompactFrame) clientFrame()       {}
func (ChatModelsFrame) clientFrame()        {}
func (ChatStatsFrame) clientFrame()         {}
func (ActivityRefreshFrame) clientFrame()   {}
func (SessionsSubscribeFrame) clientFrame() {}
func (ChatResumeFrame) clientFrame()        {}
func (ChatCloseFrame) clientFrame()         {}
func (ChatDisconnectFrame) clientFrame()    {}
func (ClientHelloFrame) clientFrame()       {}
func (u UnknownFrame) clientFrame()         {}

// ErrorCode values, from error-codes.json.
type ErrorCode = string

const (
	ErrorCodePIEof                 ErrorCode = "pi_eof"
	ErrorCodeResumeFailed          ErrorCode = "resume_failed"
	ErrorCodeSessionUnloaded       ErrorCode = "session_unloaded"
	ErrorCodeSessionMismatch       ErrorCode = "session_mismatch"
	ErrorCodePromptInFlight        ErrorCode = "prompt_in_flight"
	ErrorCodeCompactionInFlight    ErrorCode = "compaction_in_flight"
	ErrorCodeProviderError         ErrorCode = "provider_error"
	ErrorCodeUnsupportedProvider   ErrorCode = "unsupported_provider"
	ErrorCodePersistFailed         ErrorCode = "persist_failed"
	ErrorCodeDecodeFailed          ErrorCode = "decode_failed"
	ErrorCodeIncompleteHistory     ErrorCode = "incomplete_history"
	ErrorCodeExternalWriteDetected ErrorCode = "external-write-detected"
	ErrorCodeSessionActive         ErrorCode = "session-active"
	ErrorCodeAdoptionRequired      ErrorCode = "adoption_required"
	ErrorCodeBadFrame              ErrorCode = "bad_frame"
	ErrorCodeUnknownType           ErrorCode = "unknown_type"
	ErrorCodeBadCreate             ErrorCode = "bad_create"
	ErrorCodeBadProvider           ErrorCode = "bad_provider"
	ErrorCodeNoWorkspace           ErrorCode = "no_workspace"
	ErrorCodeNoChat                ErrorCode = "no_chat"
	ErrorCodeStartFailed           ErrorCode = "start_failed"
	ErrorCodeInitializeFailed      ErrorCode = "initialize_failed"
	ErrorCodeProviderOverflow      ErrorCode = "provider_overflow"
	ErrorCodeProviderTimeout       ErrorCode = "provider_timeout"
	ErrorCodeBadApproval           ErrorCode = "bad_approval"
	ErrorCodeBadResume             ErrorCode = "bad_resume"
	ErrorCodeBadSend               ErrorCode = "bad_send"
	ErrorCodeBadSet                ErrorCode = "bad_set"
	ErrorCodeSetModelFailed        ErrorCode = "set_model_failed"
	ErrorCodeSetThinkingFailed     ErrorCode = "set_thinking_failed"
	ErrorCodeApprovalFailed        ErrorCode = "approval_failed"
	ErrorCodeNoSession             ErrorCode = "no_session"
	ErrorCodeSendFailed            ErrorCode = "send_failed"
	ErrorCodeCompactFailed         ErrorCode = "compact_failed"
)

// DurableNoticeKind values, from notice-kinds.json.
type DurableNoticeKind = string

const (
	DurableNoticeKindRetryFallbackApplied   DurableNoticeKind = "retry_fallback_applied"
	DurableNoticeKindRetryFallbackReverted  DurableNoticeKind = "retry_fallback_reverted"
	DurableNoticeKindRetryFallbackSucceeded DurableNoticeKind = "retry_fallback_succeeded"
	DurableNoticeKindRetryFallbackExhausted DurableNoticeKind = "retry_fallback_exhausted"
	DurableNoticeKindServerFallbackAborted  DurableNoticeKind = "server_fallback_aborted"
	DurableNoticeKindHighReasoningWarning   DurableNoticeKind = "high_reasoning_warning"
)

// ApprovalMethod values, from shared-types.json.
type ApprovalMethod = string

const (
	ApprovalMethodSelect  ApprovalMethod = "select"
	ApprovalMethodConfirm ApprovalMethod = "confirm"
	ApprovalMethodInput   ApprovalMethod = "input"
	ApprovalMethodEditor  ApprovalMethod = "editor"
)

// NameOrigin values, from shared-types.json.
type NameOrigin = string

const (
	NameOriginAuto     NameOrigin = "auto"
	NameOriginUser     NameOrigin = "user"
	NameOriginProvider NameOrigin = "provider"
)

// RunKind values, from shared-types.json.
type RunKind = string

const (
	RunKindPrompt   RunKind = "prompt"
	RunKindSteer    RunKind = "steer"
	RunKindFollowUp RunKind = "follow_up"
)

// ToolPhase values, from shared-types.json.
type ToolPhase = string

const (
	ToolPhaseStart  ToolPhase = "start"
	ToolPhaseUpdate ToolPhase = "update"
	ToolPhaseEnd    ToolPhase = "end"
)

// UnknownFrame captures any frame whose type is not in the closed union,
// so a newer peer can send frames this build does not know (R1: drop, never fail).
type UnknownFrame struct {
	Type   string                     `json:"type"`
	Fields map[string]json.RawMessage `json:"-"`
}

func (u *UnknownFrame) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if t, ok := fields["type"]; ok {
		if err := json.Unmarshal(t, &u.Type); err != nil {
			return err
		}
	}
	delete(fields, "type")
	u.Fields = fields
	return nil
}

func (u UnknownFrame) MarshalJSON() ([]byte, error) {
	fields := make(map[string]json.RawMessage, len(u.Fields)+1)
	for k, v := range u.Fields {
		fields[k] = v
	}
	t, err := json.Marshal(u.Type)
	if err != nil {
		return nil, err
	}
	fields["type"] = t
	return json.Marshal(fields)
}

// NewServerFrame returns a fresh decoded target for a known wire type,
// or nil when the type is unknown (callers fall back to UnknownFrame).
func NewServerFrame(wireType string) ServerFrame {
	switch wireType {
	case "ready":
		return new(ReadyFrame)
	case "chat.name":
		return new(ChatNameFrame)
	case "messageDelta":
		return new(MessageDeltaFrame)
	case "message":
		return new(MessageFrame)
	case "tool":
		return new(ToolFrame)
	case "state":
		return new(StateFrame)
	case "stats":
		return new(StatsFrame)
	case "extensionEvent":
		return new(ExtensionEventFrame)
	case "sessions.activity":
		return new(SessionsActivityFrame)
	case "approval":
		return new(ApprovalFrame)
	case "commands":
		return new(CommandsFrame)
	case "models":
		return new(ModelsFrame)
	case "entries":
		return new(EntriesFrame)
	case "compaction.started":
		return new(CompactionStartedFrame)
	case "compaction.done":
		return new(CompactionDoneFrame)
	case "run.started":
		return new(RunStartedFrame)
	case "run.done":
		return new(RunDoneFrame)
	case "ack":
		return new(AckFrame)
	case "control.result":
		return new(ControlResultFrame)
	case "error":
		return new(ErrorFrame)
	case "notice":
		return new(NoticeFrame)
	case "pong":
		return new(PongFrame)
	case "hello":
		return new(HelloFrame)
	}
	return nil
}

// ParseServerFrame decodes one server from the wire. Known types decode into the
// generated struct; unknown types decode into UnknownFrame (forward compat, R1);
// malformed JSON returns an error.
func ParseServerFrame(data []byte) (ServerFrame, error) {
	var probe struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return nil, err
	}
	if probe.Type == "" {
		return nil, fmt.Errorf("frame type is required")
	}
	if target := NewServerFrame(probe.Type); target != nil {
		switch probe.Type {
		case "ready":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"piSessionId": validationSchema{AnyOf: []validationSchema{validationSchema{Type: "null"}, validationSchema{Type: "string"}}}, "resumed": validationSchema{Type: "boolean"}, "sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "ready"}}, Required: []string{"type", "sessionId", "piSessionId", "resumed"}}); err != nil {
				return nil, err
			}
		case "chat.name":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"name": validationSchema{Type: "string"}, "origin": validationSchema{Type: "string", Enum: []string{"auto", "user", "provider"}}, "sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "chat.name"}}, Required: []string{"type", "sessionId", "name", "origin"}}); err != nil {
				return nil, err
			}
		case "messageDelta":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"delta": validationSchema{Type: "object", Properties: map[string]validationSchema{"content": validationSchema{Type: "string"}, "contentIndex": validationSchema{Type: "integer"}, "delta": validationSchema{Type: "string"}, "kind": validationSchema{Type: "string"}, "partial": validationSchema{}, "reason": validationSchema{Type: "string"}}, Required: []string{"kind"}}, "messageId": validationSchema{Type: "string"}, "sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "messageDelta"}}, Required: []string{"type", "sessionId", "delta"}}); err != nil {
				return nil, err
			}
		case "message":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"message": validationSchema{Type: "object", Properties: map[string]validationSchema{"blocks": validationSchema{Type: "array", Items: &validationSchema{Type: "object", Properties: map[string]validationSchema{"arguments": validationSchema{}, "id": validationSchema{Type: "string"}, "isError": validationSchema{Type: "boolean"}, "kind": validationSchema{Type: "string"}, "name": validationSchema{Type: "string"}, "text": validationSchema{Type: "string"}, "thinking": validationSchema{Type: "string"}}, Required: []string{"kind"}}}, "content": validationSchema{Type: "string"}, "customType": validationSchema{Type: "string"}, "model": validationSchema{Type: "string"}, "role": validationSchema{Type: "string"}, "timestamp": validationSchema{Type: "number"}, "ts": validationSchema{Type: "number"}, "usage": validationSchema{}}, Required: []string{"role"}}, "sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "message"}}, Required: []string{"type", "sessionId", "message"}}); err != nil {
				return nil, err
			}
		case "tool":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"args": validationSchema{}, "isError": validationSchema{Type: "boolean"}, "partial": validationSchema{Type: "object", Properties: map[string]validationSchema{"content": validationSchema{Type: "array", Items: &validationSchema{Type: "object", Properties: map[string]validationSchema{"text": validationSchema{Type: "string"}}}}, "details": validationSchema{}}}, "phase": validationSchema{Type: "string", Enum: []string{"start", "update", "end"}}, "result": validationSchema{Type: "object", Properties: map[string]validationSchema{"content": validationSchema{Type: "array", Items: &validationSchema{Type: "object", Properties: map[string]validationSchema{"text": validationSchema{Type: "string"}}}}, "details": validationSchema{}}}, "sessionId": validationSchema{Type: "string"}, "toolCallId": validationSchema{Type: "string"}, "toolName": validationSchema{Type: "string"}, "type": validationSchema{Const: "tool"}}, Required: []string{"type", "sessionId", "toolCallId", "toolName", "phase"}}); err != nil {
				return nil, err
			}
		case "state":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"isCompacting": validationSchema{Type: "boolean"}, "isStreaming": validationSchema{Type: "boolean"}, "model": validationSchema{AnyOf: []validationSchema{validationSchema{Type: "null"}, validationSchema{Type: "object", Properties: map[string]validationSchema{"modelId": validationSchema{Type: "string"}, "provider": validationSchema{Type: "string"}}, Required: []string{"provider", "modelId"}}}}, "sessionId": validationSchema{Type: "string"}, "sessionName": validationSchema{Type: "string"}, "thinkingLevel": validationSchema{Type: "string"}, "type": validationSchema{Const: "state"}}, Required: []string{"type", "sessionId", "isStreaming", "isCompacting"}}); err != nil {
				return nil, err
			}
		case "stats":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"contextUsage": validationSchema{Type: "object", Properties: map[string]validationSchema{"contextWindow": validationSchema{Type: "integer"}, "percent": validationSchema{Type: "number"}, "tokens": validationSchema{Type: "integer"}, "total": validationSchema{Type: "integer"}, "used": validationSchema{Type: "integer"}}, Required: []string{"percent"}}, "cost": validationSchema{Type: "number"}, "sessionId": validationSchema{Type: "string"}, "tokens": validationSchema{Type: "object", Properties: map[string]validationSchema{"cacheRead": validationSchema{Type: "integer"}, "cacheWrite": validationSchema{Type: "integer"}, "input": validationSchema{Type: "integer"}, "output": validationSchema{Type: "integer"}, "total": validationSchema{Type: "integer"}}}, "type": validationSchema{Const: "stats"}}, Required: []string{"type", "sessionId"}}); err != nil {
				return nil, err
			}
		case "extensionEvent":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"data": validationSchema{}, "name": validationSchema{Type: "string"}, "sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "extensionEvent"}}, Required: []string{"type", "sessionId", "name"}}); err != nil {
				return nil, err
			}
		case "sessions.activity":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"dagDigest": validationSchema{Type: "object", Properties: map[string]validationSchema{"received_at": validationSchema{Type: "string"}, "runs": validationSchema{Type: "array", Items: &validationSchema{Type: "object", Properties: map[string]validationSchema{"run_id": validationSchema{Type: "string"}, "running_task_ids": validationSchema{Type: "array", Items: &validationSchema{Type: "string"}}, "status": validationSchema{Type: "string"}}, Required: []string{"run_id", "status", "running_task_ids"}}}, "truncated": validationSchema{Type: "boolean"}}, Required: []string{"runs", "truncated"}}, "durableSessionId": validationSchema{Type: "string"}, "overflow": validationSchema{Type: "boolean"}, "replacesSessionId": validationSchema{Type: "string"}, "sessionId": validationSchema{Type: "string"}, "snapshots": validationSchema{Type: "array", Items: &validationSchema{Type: "object", Properties: map[string]validationSchema{"data": validationSchema{}, "name": validationSchema{Type: "string", Enum: []string{"omo.task.updated", "omo.dag.updated"}}, "oversized": validationSchema{Type: "boolean"}}, Required: []string{"name", "oversized"}}}, "taskDigest": validationSchema{Type: "object", Properties: map[string]validationSchema{"received_at": validationSchema{Type: "string"}, "tasks": validationSchema{Type: "array", Items: &validationSchema{Type: "object", Properties: map[string]validationSchema{"status": validationSchema{Type: "string"}, "task_id": validationSchema{Type: "string"}, "updated_at": validationSchema{Type: "string"}}, Required: []string{"task_id", "status"}}}, "truncated": validationSchema{Type: "boolean"}}, Required: []string{"tasks", "truncated"}}, "type": validationSchema{Const: "sessions.activity"}}, Required: []string{"type", "sessionId", "durableSessionId", "snapshots", "overflow"}}); err != nil {
				return nil, err
			}
		case "approval":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"id": validationSchema{Type: "string"}, "message": validationSchema{Type: "string"}, "method": validationSchema{Type: "string", Enum: []string{"select", "confirm", "input", "editor"}}, "options": validationSchema{Type: "array", Items: &validationSchema{Type: "string"}}, "placeholder": validationSchema{Type: "string"}, "prefill": validationSchema{Type: "string"}, "sessionId": validationSchema{Type: "string"}, "timeout": validationSchema{Type: "integer"}, "title": validationSchema{Type: "string"}, "type": validationSchema{Const: "approval"}}, Required: []string{"type", "sessionId", "id", "method"}}); err != nil {
				return nil, err
			}
		case "commands":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"commands": validationSchema{Type: "array", Items: &validationSchema{Type: "object", Properties: map[string]validationSchema{"description": validationSchema{Type: "string"}, "name": validationSchema{Type: "string"}, "source": validationSchema{Type: "string"}, "sourceInfo": validationSchema{Type: "object", Properties: map[string]validationSchema{"baseDir": validationSchema{Type: "string"}, "origin": validationSchema{Type: "string"}, "path": validationSchema{Type: "string"}, "scope": validationSchema{Type: "string"}, "source": validationSchema{Type: "string"}}}, "syntax": validationSchema{Type: "string"}}, Required: []string{"name"}}}, "sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "commands"}}, Required: []string{"type", "sessionId", "commands"}}); err != nil {
				return nil, err
			}
		case "models":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"models": validationSchema{Type: "array", Items: &validationSchema{Type: "object", Properties: map[string]validationSchema{"input": validationSchema{Type: "array", Items: &validationSchema{Type: "string"}}, "modelId": validationSchema{Type: "string"}, "name": validationSchema{Type: "string"}, "provider": validationSchema{Type: "string"}}, Required: []string{"provider", "modelId"}}}, "sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "models"}}, Required: []string{"type", "sessionId", "models"}}); err != nil {
				return nil, err
			}
		case "entries":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"entries": validationSchema{Type: "array", Items: &validationSchema{}}, "final": validationSchema{Type: "boolean"}, "leafId": validationSchema{Type: "string"}, "sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "entries"}}, Required: []string{"type", "sessionId", "entries", "final"}}); err != nil {
				return nil, err
			}
		case "compaction.started":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "compaction.started"}}, Required: []string{"type", "sessionId"}}); err != nil {
				return nil, err
			}
		case "compaction.done":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"error": validationSchema{Type: "string"}, "sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "compaction.done"}}, Required: []string{"type", "sessionId"}}); err != nil {
				return nil, err
			}
		case "run.started":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "run.started"}}, Required: []string{"type", "sessionId"}}); err != nil {
				return nil, err
			}
		case "run.done":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"reason": validationSchema{Type: "string"}, "sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "run.done"}}, Required: []string{"type", "sessionId", "reason"}}); err != nil {
				return nil, err
			}
		case "ack":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"command": validationSchema{Type: "string"}, "id": validationSchema{Type: "string"}, "requestId": validationSchema{Type: "string"}, "sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "ack"}}, Required: []string{"type", "command"}}); err != nil {
				return nil, err
			}
		case "control.result":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"command": validationSchema{Type: "string"}, "message": validationSchema{Type: "string"}, "requestId": validationSchema{Type: "string"}, "sessionId": validationSchema{Type: "string"}, "success": validationSchema{Type: "boolean"}, "type": validationSchema{Const: "control.result"}}, Required: []string{"type", "sessionId", "command", "success"}}); err != nil {
				return nil, err
			}
		case "error":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"candidates": validationSchema{Type: "array", Items: &validationSchema{Type: "object", Properties: map[string]validationSchema{"hostPath": validationSchema{Type: "string"}, "id": validationSchema{Type: "string"}, "name": validationSchema{Type: "string"}}, Required: []string{"id", "name"}}}, "code": validationSchema{Type: "string", Enum: []string{"pi_eof", "resume_failed", "session_unloaded", "session_mismatch", "prompt_in_flight", "compaction_in_flight", "provider_error", "unsupported_provider", "persist_failed", "decode_failed", "incomplete_history", "external-write-detected", "session-active", "adoption_required", "bad_frame", "unknown_type", "bad_create", "bad_provider", "no_workspace", "no_chat", "start_failed", "initialize_failed", "provider_overflow", "provider_timeout", "bad_approval", "bad_resume", "bad_send", "bad_set", "set_model_failed", "set_thinking_failed", "approval_failed", "no_session", "send_failed", "compact_failed"}}, "command": validationSchema{Type: "string"}, "dangling": validationSchema{Type: "boolean"}, "knownLeaf": validationSchema{Type: "string"}, "message": validationSchema{Type: "string"}, "observedLeaf": validationSchema{Type: "string"}, "requestId": validationSchema{Type: "string"}, "sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "error"}}, Required: []string{"type", "message"}}); err != nil {
				return nil, err
			}
		case "notice":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"at": validationSchema{Type: "string", Format: "rfc3339nano"}, "kind": validationSchema{Type: "string"}, "nid": validationSchema{Type: "string"}, "payload": validationSchema{}, "sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "notice"}}, Required: []string{"type", "sessionId", "kind", "at"}}); err != nil {
				return nil, err
			}
		case "pong":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "pong"}}, Required: []string{"type"}}); err != nil {
				return nil, err
			}
		case "hello":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"serverVersion": validationSchema{Type: "string"}, "type": validationSchema{Const: "hello"}, "version": validationSchema{Type: "integer"}}, Required: []string{"type", "version", "serverVersion"}}); err != nil {
				return nil, err
			}
		}
		if err := json.Unmarshal(data, target); err != nil {
			return nil, err
		}
		return target, nil
	}
	var u UnknownFrame
	if err := json.Unmarshal(data, &u); err != nil {
		return nil, err
	}
	return u, nil
}

// ServerFrameTypes lists every known wire type in the closed union.
func ServerFrameTypes() []string {
	return []string{
		"ready",
		"chat.name",
		"messageDelta",
		"message",
		"tool",
		"state",
		"stats",
		"extensionEvent",
		"sessions.activity",
		"approval",
		"commands",
		"models",
		"entries",
		"compaction.started",
		"compaction.done",
		"run.started",
		"run.done",
		"ack",
		"control.result",
		"error",
		"notice",
		"pong",
		"hello",
	}
}

// NewClientFrame returns a fresh decoded target for a known wire type,
// or nil when the type is unknown (callers fall back to UnknownFrame).
func NewClientFrame(wireType string) ClientFrame {
	switch wireType {
	case "ping":
		return new(PingFrame)
	case "chat.create":
		return new(ChatCreateFrame)
	case "chat.send":
		return new(ChatSendFrame)
	case "chat.abort":
		return new(ChatAbortFrame)
	case "chat.set":
		return new(ChatSetFrame)
	case "approval.respond":
		return new(ApprovalRespondFrame)
	case "chat.commands":
		return new(ChatCommandsFrame)
	case "chat.compact":
		return new(ChatCompactFrame)
	case "chat.models":
		return new(ChatModelsFrame)
	case "chat.stats":
		return new(ChatStatsFrame)
	case "activity.refresh":
		return new(ActivityRefreshFrame)
	case "sessions.subscribe":
		return new(SessionsSubscribeFrame)
	case "chat.resume":
		return new(ChatResumeFrame)
	case "chat.close":
		return new(ChatCloseFrame)
	case "chat.disconnect":
		return new(ChatDisconnectFrame)
	case "hello":
		return new(ClientHelloFrame)
	}
	return nil
}

// ParseClientFrame decodes one client from the wire. Known types decode into the
// generated struct; unknown types decode into UnknownFrame (forward compat, R1);
// malformed JSON returns an error.
func ParseClientFrame(data []byte) (ClientFrame, error) {
	var probe struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return nil, err
	}
	if probe.Type == "" {
		return nil, fmt.Errorf("frame type is required")
	}
	if target := NewClientFrame(probe.Type); target != nil {
		switch probe.Type {
		case "ping":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"type": validationSchema{Const: "ping"}}, Required: []string{"type"}}); err != nil {
				return nil, err
			}
		case "chat.create":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"chatId": validationSchema{Type: "string"}, "recovery": validationSchema{Type: "boolean"}, "type": validationSchema{Const: "chat.create"}, "wsId": validationSchema{Type: "string"}}, Required: []string{"type", "wsId", "chatId"}}); err != nil {
				return nil, err
			}
		case "chat.send":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"run": validationSchema{Type: "object", Properties: map[string]validationSchema{"images": validationSchema{Type: "array", Items: &validationSchema{Type: "object", Properties: map[string]validationSchema{"data": validationSchema{Type: "string"}, "mimeType": validationSchema{Type: "string"}}, Required: []string{"data", "mimeType"}}}, "kind": validationSchema{Type: "string", Enum: []string{"prompt", "steer", "follow_up"}}, "message": validationSchema{Type: "string"}}, Required: []string{"kind", "message"}}, "sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "chat.send"}}, Required: []string{"type", "sessionId", "run"}}); err != nil {
				return nil, err
			}
		case "chat.abort":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "chat.abort"}}, Required: []string{"type", "sessionId"}}); err != nil {
				return nil, err
			}
		case "chat.set":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"model": validationSchema{Type: "object", Properties: map[string]validationSchema{"modelId": validationSchema{Type: "string"}, "provider": validationSchema{Type: "string"}}, Required: []string{"provider", "modelId"}}, "requestId": validationSchema{Type: "string"}, "sessionId": validationSchema{Type: "string"}, "thinkingLevel": validationSchema{Type: "string"}, "type": validationSchema{Const: "chat.set"}}, Required: []string{"type", "sessionId"}}); err != nil {
				return nil, err
			}
		case "approval.respond":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"cancelled": validationSchema{Type: "boolean"}, "confirmed": validationSchema{Type: "boolean"}, "id": validationSchema{Type: "string"}, "requestId": validationSchema{Type: "string"}, "sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "approval.respond"}, "value": validationSchema{Type: "string"}}, Required: []string{"type", "sessionId", "id"}}); err != nil {
				return nil, err
			}
		case "chat.commands":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "chat.commands"}}, Required: []string{"type", "sessionId"}}); err != nil {
				return nil, err
			}
		case "chat.compact":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "chat.compact"}}, Required: []string{"type", "sessionId"}}); err != nil {
				return nil, err
			}
		case "chat.models":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "chat.models"}}, Required: []string{"type", "sessionId"}}); err != nil {
				return nil, err
			}
		case "chat.stats":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "chat.stats"}}, Required: []string{"type", "sessionId"}}); err != nil {
				return nil, err
			}
		case "activity.refresh":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "activity.refresh"}}, Required: []string{"type", "sessionId"}}); err != nil {
				return nil, err
			}
		case "sessions.subscribe":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"mode": validationSchema{Type: "string", Enum: []string{"all_live", "explicit", "none"}}, "sessionIds": validationSchema{Type: "array", Items: &validationSchema{Type: "string"}}, "type": validationSchema{Const: "sessions.subscribe"}}, Required: []string{"type", "mode"}}); err != nil {
				return nil, err
			}
		case "chat.resume":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"sessionId": validationSchema{Type: "string"}, "since": validationSchema{Type: "string"}, "type": validationSchema{Const: "chat.resume"}}, Required: []string{"type", "sessionId"}}); err != nil {
				return nil, err
			}
		case "chat.close":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "chat.close"}}, Required: []string{"type", "sessionId"}}); err != nil {
				return nil, err
			}
		case "chat.disconnect":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"sessionId": validationSchema{Type: "string"}, "type": validationSchema{Const: "chat.disconnect"}}, Required: []string{"type", "sessionId"}}); err != nil {
				return nil, err
			}
		case "hello":
			if err := validateFrameJSON(data, validationSchema{Type: "object", Properties: map[string]validationSchema{"type": validationSchema{Const: "hello"}, "version": validationSchema{Type: "integer"}}, Required: []string{"type", "version"}}); err != nil {
				return nil, err
			}
		}
		if err := json.Unmarshal(data, target); err != nil {
			return nil, err
		}
		return target, nil
	}
	var u UnknownFrame
	if err := json.Unmarshal(data, &u); err != nil {
		return nil, err
	}
	return u, nil
}

// ClientFrameTypes lists every known wire type in the closed union.
func ClientFrameTypes() []string {
	return []string{
		"ping",
		"chat.create",
		"chat.send",
		"chat.abort",
		"chat.set",
		"approval.respond",
		"chat.commands",
		"chat.compact",
		"chat.models",
		"chat.stats",
		"activity.refresh",
		"sessions.subscribe",
		"chat.resume",
		"chat.close",
		"chat.disconnect",
		"hello",
	}
}

// FrameKindToWireName maps a v2 session FrameKind to the wire type emitted on the
// socket (v1 continuity; owned by the bridge).
var FrameKindToWireName = map[string]string{
	"ack":                "ack",
	"approval":           "approval",
	"commands":           "commands",
	"compaction.done":    "compaction.done",
	"compaction.started": "compaction.started",
	"control.result":     "control.result",
	"entries":            "entries",
	"error":              "error",
	"extensionEvent":     "extensionEvent",
	"message":            "message",
	"message.delta":      "messageDelta",
	"models":             "models",
	"name":               "chat.name",
	"notice":             "notice",
	"ready":              "ready",
	"run.done":           "run.done",
	"run.started":        "run.started",
	"state":              "state",
	"stats":              "stats",
	"tool":               "tool",
}

// ClientWireNames lists the client->server command names (identity mapping).
// ping and hello are connection-level and need no session.
var ClientWireNames = map[string]string{
	"activity.refresh":   "activity.refresh",
	"approval.respond":   "approval.respond",
	"chat.abort":         "chat.abort",
	"chat.close":         "chat.close",
	"chat.commands":      "chat.commands",
	"chat.compact":       "chat.compact",
	"chat.create":        "chat.create",
	"chat.disconnect":    "chat.disconnect",
	"chat.models":        "chat.models",
	"chat.resume":        "chat.resume",
	"chat.send":          "chat.send",
	"chat.set":           "chat.set",
	"chat.stats":         "chat.stats",
	"ping":               "ping",
	"sessions.subscribe": "sessions.subscribe",
}
