// Code generated by contract/gen_go.go from contract/schemas; DO NOT EDIT.
//
// Single-source WS contract for v2: wire names keep v1 continuity,
// v2 session FrameKind -> wire name mapping is FrameKindToWireName.
// Regenerate with: go generate ./contract (Go) and node contract/gen_ts.mjs (TS).

package wscontract

import "encoding/json"

type AssistantDelta struct {
	Content      *string         `json:"content,omitempty"`
	ContentIndex *int64          `json:"contentIndex,omitempty"`
	Delta        *string         `json:"delta,omitempty"`
	Kind         string          `json:"kind"`
	Partial      json.RawMessage `json:"partial,omitempty"`
	Reason       *string         `json:"reason,omitempty"`
}

type AssistantMessage struct {
	Blocks     []ContentBlock  `json:"blocks,omitempty"`
	CustomType *string         `json:"customType,omitempty"`
	Model      *string         `json:"model,omitempty"`
	Role       string          `json:"role"`
	Ts         *float64        `json:"ts,omitempty"`
	Usage      json.RawMessage `json:"usage,omitempty"`
}

type ChatImage struct {
	Data     string `json:"data"`
	MimeType string `json:"mimeType"`
}

type CommandEntry struct {
	Description *string            `json:"description,omitempty"`
	Name        string             `json:"name"`
	Source      *string            `json:"source,omitempty"`
	SourceInfo  *CommandSourceInfo `json:"sourceInfo,omitempty"`
	Syntax      *string            `json:"syntax,omitempty"`
}

type CommandSourceInfo struct {
	BaseDir *string `json:"baseDir,omitempty"`
	Origin  *string `json:"origin,omitempty"`
	Path    *string `json:"path,omitempty"`
	Scope   *string `json:"scope,omitempty"`
	Source  *string `json:"source,omitempty"`
}

type ContentBlock struct {
	Arguments json.RawMessage `json:"arguments,omitempty"`
	ID        *string         `json:"id,omitempty"`
	IsError   *bool           `json:"isError,omitempty"`
	Kind      string          `json:"kind"`
	Name      *string         `json:"name,omitempty"`
	Text      *string         `json:"text,omitempty"`
	Thinking  *string         `json:"thinking,omitempty"`
}

type ContextUsage struct {
	ContextWindow int64   `json:"contextWindow"`
	Percent       float64 `json:"percent"`
	Tokens        int64   `json:"tokens"`
}

type ModelInfo struct {
	Input    []string `json:"input,omitempty"`
	ModelID  string   `json:"modelId"`
	Name     *string  `json:"name,omitempty"`
	Provider string   `json:"provider"`
}

type ModelRef struct {
	ModelID  string `json:"modelId"`
	Provider string `json:"provider"`
}

type ResumeCandidate struct {
	HostPath *string `json:"hostPath,omitempty"`
	ID       string  `json:"id"`
	Name     string  `json:"name"`
}

type ToolPayloadContentItem struct {
	Text *string `json:"text,omitempty"`
}

type ToolPayload struct {
	Content []ToolPayloadContentItem `json:"content,omitempty"`
	Details json.RawMessage          `json:"details,omitempty"`
}

type ClientHelloFrame struct {
	Type string `json:"type"`
	// Wire contract version the client expects
	Version int64 `json:"version"`
}

type HelloFrame struct {
	// Human-readable server build identity
	ServerVersion string `json:"serverVersion"`
	Type          string `json:"type"`
	// Wire contract version this server speaks
	Version int64 `json:"version"`
}

type AckFrame struct {
	Command string  `json:"command"`
	ID      *string `json:"id,omitempty"`
	// Correlates with the client request (invariant 19)
	RequestID *string `json:"requestId,omitempty"`
	SessionID *string `json:"sessionId,omitempty"`
	Type      string  `json:"type"`
}

type ApprovalFrame struct {
	ID          string         `json:"id"`
	Message     *string        `json:"message,omitempty"`
	Method      ApprovalMethod `json:"method"`
	Options     []string       `json:"options,omitempty"`
	Placeholder *string        `json:"placeholder,omitempty"`
	Prefill     *string        `json:"prefill,omitempty"`
	SessionID   string         `json:"sessionId"`
	Timeout     *int64         `json:"timeout,omitempty"`
	Title       *string        `json:"title,omitempty"`
	Type        string         `json:"type"`
}

type ChatNameFrame struct {
	Name      string     `json:"name"`
	Origin    NameOrigin `json:"origin"`
	SessionID string     `json:"sessionId"`
	Type      string     `json:"type"`
}

type CommandsFrame struct {
	Commands  []CommandEntry `json:"commands"`
	SessionID string         `json:"sessionId"`
	Type      string         `json:"type"`
}

type CompactionDoneFrame struct {
	Error     *string `json:"error,omitempty"`
	SessionID string  `json:"sessionId"`
	Type      string  `json:"type"`
}

type CompactionStartedFrame struct {
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
}

type ControlResultFrame struct {
	Command   string  `json:"command"`
	Message   *string `json:"message,omitempty"`
	RequestID *string `json:"requestId,omitempty"`
	SessionID string  `json:"sessionId"`
	Success   bool    `json:"success"`
	Type      string  `json:"type"`
}

type EntriesFrame struct {
	// History entries; bounds per invariant 18 (100 entries / 256 KiB per page)
	Entries []json.RawMessage `json:"entries"`
	// REQUIRED on every entries frame (invariant 18)
	Final bool `json:"final"`
	// Present only on the terminal page
	LeafID    *string `json:"leafId,omitempty"`
	SessionID string  `json:"sessionId"`
	Type      string  `json:"type"`
}

type ErrorFrame struct {
	// resume_failed only: scanned branch candidates
	Candidates []ResumeCandidate `json:"candidates,omitempty"`
	Code       *ErrorCode        `json:"code,omitempty"`
	// FailedRpcCommand — provider command string, open on purpose
	Command *string `json:"command,omitempty"`
	// resume_failed only: stored identity path no longer exists
	Dangling  *bool   `json:"dangling,omitempty"`
	Message   string  `json:"message"`
	RequestID *string `json:"requestId,omitempty"`
	SessionID *string `json:"sessionId,omitempty"`
	Type      string  `json:"type"`
}

type ExtensionEventFrame struct {
	Data      json.RawMessage `json:"data,omitempty"`
	Name      string          `json:"name"`
	SessionID string          `json:"sessionId"`
	Type      string          `json:"type"`
}

type MessageDeltaFrame struct {
	Delta     AssistantDelta `json:"delta"`
	MessageID *string        `json:"messageId,omitempty"`
	SessionID string         `json:"sessionId"`
	Type      string         `json:"type"`
}

type MessageFrame struct {
	Message   AssistantMessage `json:"message"`
	SessionID string           `json:"sessionId"`
	Type      string           `json:"type"`
}

type ModelsFrame struct {
	Models    []ModelInfo `json:"models"`
	SessionID string      `json:"sessionId"`
	Type      string      `json:"type"`
}

type NoticeFrame struct {
	// RFC3339Nano receipt time; every notice carries one (invariant 14)
	At string `json:"at"`
	// Open set: durable kinds are enumerated in notice-kinds.json; everything else is transient
	Kind string `json:"kind"`
	// Server-assigned replay identity for durable notices
	Nid       *string         `json:"nid,omitempty"`
	Payload   json.RawMessage `json:"payload,omitempty"`
	SessionID string          `json:"sessionId"`
	Type      string          `json:"type"`
}

type PongFrame struct {
	SessionID *string `json:"sessionId,omitempty"`
	Type      string  `json:"type"`
}

type ReadyFrame struct {
	PISessionID string `json:"piSessionId"`
	Resumed     bool   `json:"resumed"`
	SessionID   string `json:"sessionId"`
	Type        string `json:"type"`
}

type RunDoneFrame struct {
	Reason    string `json:"reason"`
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
}

type RunStartedFrame struct {
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
}

type StateFrame struct {
	IsCompacting  bool      `json:"isCompacting"`
	IsStreaming   bool      `json:"isStreaming"`
	Model         *ModelRef `json:"model,omitempty"`
	SessionID     string    `json:"sessionId"`
	SessionName   *string   `json:"sessionName,omitempty"`
	ThinkingLevel *string   `json:"thinkingLevel,omitempty"`
	Type          string    `json:"type"`
}

type StatsFrame struct {
	ContextUsage *ContextUsage   `json:"contextUsage,omitempty"`
	Cost         *float64        `json:"cost,omitempty"`
	SessionID    string          `json:"sessionId"`
	Tokens       json.RawMessage `json:"tokens,omitempty"`
	Type         string          `json:"type"`
}

type ToolFrame struct {
	Args       json.RawMessage `json:"args,omitempty"`
	IsError    *bool           `json:"isError,omitempty"`
	Partial    *ToolPayload    `json:"partial,omitempty"`
	Phase      ToolPhase       `json:"phase"`
	Result     *ToolPayload    `json:"result,omitempty"`
	SessionID  string          `json:"sessionId"`
	ToolCallID string          `json:"toolCallId"`
	ToolName   string          `json:"toolName"`
	Type       string          `json:"type"`
}

type ActivityRefreshFrame struct {
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
}

type ApprovalRespondFrame struct {
	Cancelled *bool   `json:"cancelled,omitempty"`
	Confirmed *bool   `json:"confirmed,omitempty"`
	ID        string  `json:"id"`
	RequestID *string `json:"requestId,omitempty"`
	SessionID string  `json:"sessionId"`
	Type      string  `json:"type"`
	Value     *string `json:"value,omitempty"`
}

type ChatAbortFrame struct {
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
}

type ChatCloseFrame struct {
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
}

type ChatCommandsFrame struct {
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
}

type ChatCompactFrame struct {
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
}

type ChatCreateFrame struct {
	ChatID string `json:"chatId"`
	Type   string `json:"type"`
	WsID   string `json:"wsId"`
}

type ChatDisconnectFrame struct {
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
}

type ChatModelsFrame struct {
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
}

type ChatResumeFrame struct {
	SessionID string  `json:"sessionId"`
	Since     *string `json:"since,omitempty"`
	Type      string  `json:"type"`
}

type ChatSendFrameRun struct {
	Images  []ChatImage `json:"images,omitempty"`
	Kind    RunKind     `json:"kind"`
	Message string      `json:"message"`
}

type ChatSendFrame struct {
	Run       ChatSendFrameRun `json:"run"`
	SessionID string           `json:"sessionId"`
	Type      string           `json:"type"`
}

type ChatSetFrame struct {
	Model         *ModelRef `json:"model,omitempty"`
	RequestID     *string   `json:"requestId,omitempty"`
	SessionID     string    `json:"sessionId"`
	ThinkingLevel *string   `json:"thinkingLevel,omitempty"`
	Type          string    `json:"type"`
}

type ChatStatsFrame struct {
	SessionID string `json:"sessionId"`
	Type      string `json:"type"`
}

type PingFrame struct {
	Type string `json:"type"`
}

// ServerFrame is implemented by every server->client frame struct.
type ServerFrame interface{ serverFrame() }

// ClientFrame is implemented by every client->server frame struct.
type ClientFrame interface{ clientFrame() }

func (ReadyFrame) serverFrame()             {}
func (ChatNameFrame) serverFrame()          {}
func (MessageDeltaFrame) serverFrame()      {}
func (MessageFrame) serverFrame()           {}
func (ToolFrame) serverFrame()              {}
func (StateFrame) serverFrame()             {}
func (StatsFrame) serverFrame()             {}
func (ExtensionEventFrame) serverFrame()    {}
func (ApprovalFrame) serverFrame()          {}
func (CommandsFrame) serverFrame()          {}
func (ModelsFrame) serverFrame()            {}
func (EntriesFrame) serverFrame()           {}
func (CompactionStartedFrame) serverFrame() {}
func (CompactionDoneFrame) serverFrame()    {}
func (RunStartedFrame) serverFrame()        {}
func (RunDoneFrame) serverFrame()           {}
func (AckFrame) serverFrame()               {}
func (ControlResultFrame) serverFrame()     {}
func (ErrorFrame) serverFrame()             {}
func (NoticeFrame) serverFrame()            {}
func (PongFrame) serverFrame()              {}
func (HelloFrame) serverFrame()             {}
func (u UnknownFrame) serverFrame()         {}

func (PingFrame) clientFrame()            {}
func (ChatCreateFrame) clientFrame()      {}
func (ChatSendFrame) clientFrame()        {}
func (ChatAbortFrame) clientFrame()       {}
func (ChatSetFrame) clientFrame()         {}
func (ApprovalRespondFrame) clientFrame() {}
func (ChatCommandsFrame) clientFrame()    {}
func (ChatCompactFrame) clientFrame()     {}
func (ChatModelsFrame) clientFrame()      {}
func (ChatStatsFrame) clientFrame()       {}
func (ActivityRefreshFrame) clientFrame() {}
func (ChatResumeFrame) clientFrame()      {}
func (ChatCloseFrame) clientFrame()       {}
func (ChatDisconnectFrame) clientFrame()  {}
func (ClientHelloFrame) clientFrame()     {}
func (u UnknownFrame) clientFrame()       {}

// ErrorCode values, from error-codes.json.
type ErrorCode = string

const (
	ErrorCodePIEof              ErrorCode = "pi_eof"
	ErrorCodeResumeFailed       ErrorCode = "resume_failed"
	ErrorCodeSessionUnloaded    ErrorCode = "session_unloaded"
	ErrorCodeSessionMismatch    ErrorCode = "session_mismatch"
	ErrorCodePromptInFlight     ErrorCode = "prompt_in_flight"
	ErrorCodeCompactionInFlight ErrorCode = "compaction_in_flight"
	ErrorCodeProviderError      ErrorCode = "provider_error"
	ErrorCodePersistFailed      ErrorCode = "persist_failed"
	ErrorCodeDecodeFailed       ErrorCode = "decode_failed"
	ErrorCodeBadFrame           ErrorCode = "bad_frame"
	ErrorCodeUnknownType        ErrorCode = "unknown_type"
	ErrorCodeBadCreate          ErrorCode = "bad_create"
	ErrorCodeBadProvider        ErrorCode = "bad_provider"
	ErrorCodeNoWorkspace        ErrorCode = "no_workspace"
	ErrorCodeNoChat             ErrorCode = "no_chat"
	ErrorCodeStartFailed        ErrorCode = "start_failed"
)

// DurableNoticeKind values, from notice-kinds.json.
type DurableNoticeKind = string

const (
	DurableNoticeKindRetryFallbackApplied   DurableNoticeKind = "retry_fallback_applied"
	DurableNoticeKindRetryFallbackReverted  DurableNoticeKind = "retry_fallback_reverted"
	DurableNoticeKindRetryFallbackSucceeded DurableNoticeKind = "retry_fallback_succeeded"
	DurableNoticeKindRetryFallbackExhausted DurableNoticeKind = "retry_fallback_exhausted"
	DurableNoticeKindServerFallbackAborted  DurableNoticeKind = "server_fallback_aborted"
	DurableNoticeKindHighReasoningWarning   DurableNoticeKind = "high_reasoning_warning"
)

// ApprovalMethod values, from shared-types.json.
type ApprovalMethod = string

const (
	ApprovalMethodSelect  ApprovalMethod = "select"
	ApprovalMethodConfirm ApprovalMethod = "confirm"
	ApprovalMethodInput   ApprovalMethod = "input"
	ApprovalMethodEditor  ApprovalMethod = "editor"
)

// NameOrigin values, from shared-types.json.
type NameOrigin = string

const (
	NameOriginAuto     NameOrigin = "auto"
	NameOriginUser     NameOrigin = "user"
	NameOriginProvider NameOrigin = "provider"
)

// RunKind values, from shared-types.json.
type RunKind = string

const (
	RunKindPrompt   RunKind = "prompt"
	RunKindSteer    RunKind = "steer"
	RunKindFollowUp RunKind = "follow_up"
)

// ToolPhase values, from shared-types.json.
type ToolPhase = string

const (
	ToolPhaseStart  ToolPhase = "start"
	ToolPhaseUpdate ToolPhase = "update"
	ToolPhaseEnd    ToolPhase = "end"
)

// UnknownFrame captures any frame whose type is not in the closed union,
// so a newer peer can send frames this build does not know (R1: drop, never fail).
type UnknownFrame struct {
	Type   string                     `json:"type"`
	Fields map[string]json.RawMessage `json:"-"`
}

func (u *UnknownFrame) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if t, ok := fields["type"]; ok {
		if err := json.Unmarshal(t, &u.Type); err != nil {
			return err
		}
	}
	delete(fields, "type")
	u.Fields = fields
	return nil
}

func (u UnknownFrame) MarshalJSON() ([]byte, error) {
	fields := make(map[string]json.RawMessage, len(u.Fields)+1)
	for k, v := range u.Fields {
		fields[k] = v
	}
	t, err := json.Marshal(u.Type)
	if err != nil {
		return nil, err
	}
	fields["type"] = t
	return json.Marshal(fields)
}

// NewServerFrame returns a fresh decoded target for a known wire type,
// or nil when the type is unknown (callers fall back to UnknownFrame).
func NewServerFrame(wireType string) ServerFrame {
	switch wireType {
	case "ready":
		return new(ReadyFrame)
	case "chat.name":
		return new(ChatNameFrame)
	case "messageDelta":
		return new(MessageDeltaFrame)
	case "message":
		return new(MessageFrame)
	case "tool":
		return new(ToolFrame)
	case "state":
		return new(StateFrame)
	case "stats":
		return new(StatsFrame)
	case "extensionEvent":
		return new(ExtensionEventFrame)
	case "approval":
		return new(ApprovalFrame)
	case "commands":
		return new(CommandsFrame)
	case "models":
		return new(ModelsFrame)
	case "entries":
		return new(EntriesFrame)
	case "compaction.started":
		return new(CompactionStartedFrame)
	case "compaction.done":
		return new(CompactionDoneFrame)
	case "run.started":
		return new(RunStartedFrame)
	case "run.done":
		return new(RunDoneFrame)
	case "ack":
		return new(AckFrame)
	case "control.result":
		return new(ControlResultFrame)
	case "error":
		return new(ErrorFrame)
	case "notice":
		return new(NoticeFrame)
	case "pong":
		return new(PongFrame)
	case "hello":
		return new(HelloFrame)
	}
	return nil
}

// ParseServerFrame decodes one server from the wire. Known types decode into the
// generated struct; unknown types decode into UnknownFrame (forward compat, R1);
// malformed JSON returns an error.
func ParseServerFrame(data []byte) (ServerFrame, error) {
	var probe struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return nil, err
	}
	if target := NewServerFrame(probe.Type); target != nil {
		if err := json.Unmarshal(data, target); err != nil {
			return nil, err
		}
		return target, nil
	}
	var u UnknownFrame
	if err := json.Unmarshal(data, &u); err != nil {
		return nil, err
	}
	return u, nil
}

// ServerFrameTypes lists every known wire type in the closed union.
func ServerFrameTypes() []string {
	return []string{
		"ready",
		"chat.name",
		"messageDelta",
		"message",
		"tool",
		"state",
		"stats",
		"extensionEvent",
		"approval",
		"commands",
		"models",
		"entries",
		"compaction.started",
		"compaction.done",
		"run.started",
		"run.done",
		"ack",
		"control.result",
		"error",
		"notice",
		"pong",
		"hello",
	}
}

// NewClientFrame returns a fresh decoded target for a known wire type,
// or nil when the type is unknown (callers fall back to UnknownFrame).
func NewClientFrame(wireType string) ClientFrame {
	switch wireType {
	case "ping":
		return new(PingFrame)
	case "chat.create":
		return new(ChatCreateFrame)
	case "chat.send":
		return new(ChatSendFrame)
	case "chat.abort":
		return new(ChatAbortFrame)
	case "chat.set":
		return new(ChatSetFrame)
	case "approval.respond":
		return new(ApprovalRespondFrame)
	case "chat.commands":
		return new(ChatCommandsFrame)
	case "chat.compact":
		return new(ChatCompactFrame)
	case "chat.models":
		return new(ChatModelsFrame)
	case "chat.stats":
		return new(ChatStatsFrame)
	case "activity.refresh":
		return new(ActivityRefreshFrame)
	case "chat.resume":
		return new(ChatResumeFrame)
	case "chat.close":
		return new(ChatCloseFrame)
	case "chat.disconnect":
		return new(ChatDisconnectFrame)
	case "hello":
		return new(ClientHelloFrame)
	}
	return nil
}

// ParseClientFrame decodes one client from the wire. Known types decode into the
// generated struct; unknown types decode into UnknownFrame (forward compat, R1);
// malformed JSON returns an error.
func ParseClientFrame(data []byte) (ClientFrame, error) {
	var probe struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return nil, err
	}
	if target := NewClientFrame(probe.Type); target != nil {
		if err := json.Unmarshal(data, target); err != nil {
			return nil, err
		}
		return target, nil
	}
	var u UnknownFrame
	if err := json.Unmarshal(data, &u); err != nil {
		return nil, err
	}
	return u, nil
}

// ClientFrameTypes lists every known wire type in the closed union.
func ClientFrameTypes() []string {
	return []string{
		"ping",
		"chat.create",
		"chat.send",
		"chat.abort",
		"chat.set",
		"approval.respond",
		"chat.commands",
		"chat.compact",
		"chat.models",
		"chat.stats",
		"activity.refresh",
		"chat.resume",
		"chat.close",
		"chat.disconnect",
		"hello",
	}
}

// FrameKindToWireName maps a v2 session FrameKind to the wire type emitted on the
// socket (v1 continuity; owned by the bridge).
var FrameKindToWireName = map[string]string{
	"ack":                "ack",
	"approval":           "approval",
	"commands":           "commands",
	"compaction.done":    "compaction.done",
	"compaction.started": "compaction.started",
	"control.result":     "control.result",
	"entries":            "entries",
	"error":              "error",
	"extensionEvent":     "extensionEvent",
	"message":            "message",
	"message.delta":      "messageDelta",
	"models":             "models",
	"name":               "chat.name",
	"notice":             "notice",
	"ready":              "ready",
	"run.done":           "run.done",
	"run.started":        "run.started",
	"state":              "state",
	"stats":              "stats",
	"tool":               "tool",
}

// ClientWireNames lists the client->server command names (identity mapping).
// ping and hello are connection-level and need no session.
var ClientWireNames = map[string]string{
	"activity.refresh": "activity.refresh",
	"approval.respond": "approval.respond",
	"chat.abort":       "chat.abort",
	"chat.close":       "chat.close",
	"chat.commands":    "chat.commands",
	"chat.compact":     "chat.compact",
	"chat.create":      "chat.create",
	"chat.disconnect":  "chat.disconnect",
	"chat.models":      "chat.models",
	"chat.resume":      "chat.resume",
	"chat.send":        "chat.send",
	"chat.set":         "chat.set",
	"chat.stats":       "chat.stats",
	"ping":             "ping",
}
