#!/usr/bin/env node
// Generates frontend/src/lib/contract/types_gen.ts from the JSON Schemas in
// contract/schemas/ — the same single source gen_go.go reads. Run:
//   node contract/gen_ts.mjs
// Output is committed; there is no runtime codegen.
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const schemasDir = join(here, "schemas");
const outPath = join(here, "..", "frontend", "src", "lib", "contract", "types_gen.ts");

const files = new Map();
async function load(fileID) {
  if (!files.has(fileID)) {
    files.set(fileID, JSON.parse(await readFile(join(schemasDir, fileID), "utf8")));
  }
  return files.get(fileID);
}

function defName(ref) {
  const i = ref.lastIndexOf("/");
  return ref.slice(i + 1);
}

function resolveRef(ref, ctxFile) {
  let fileID = ctxFile;
  let rest = ref;
  const i = ref.indexOf("#");
  if (i >= 0) {
    if (ref.slice(0, i) !== "") fileID = ref.slice(0, i);
    rest = ref.slice(i + 1);
  }
  let node = doc(fileID);
  for (const part of rest.split("/").filter(Boolean)) {
    node = node[part];
  }
  return node;
}

function doc(fileID) {
  // sync wrapper over the preloaded cache
  if (!files.has(fileID)) throw new Error(`schema ${fileID} not preloaded`);
  return files.get(fileID);
}

const OPAQUE_KEYS = ["type", "properties", "items", "enum", "const", "anyOf", "$ref"];
function isOpaque(node) {
  return !OPAQUE_KEYS.some((k) => k in node);
}

// tsType maps a schema node to a TypeScript type expression.
function tsType(node, ctxFile) {
  if ("$ref" in node) {
    if (isOpaque(resolveRef(node.$ref, ctxFile))) return "JsonValue";
    return defName(node.$ref);
  }
  if ("anyOf" in node) {
    const nonNull = node.anyOf.filter((b) => b?.type !== "null");
    if (nonNull.length === 1) return `${tsType(nonNull[0], ctxFile)} | null`;
    return "JsonValue";
  }
  if ("const" in node) return JSON.stringify(node.const);
  if ("enum" in node) return node.enum.map((v) => JSON.stringify(v)).join(" | ");
  switch (node.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "array":
      return `readonly ${tsType(node.items ?? {}, ctxFile)}[]`;
    case "object":
      return tsObjectLiteral(node, ctxFile);
    default:
      return "JsonValue";
  }
}

function tsObjectLiteral(node, ctxFile) {
  const required = new Set(node.required ?? []);
  const props = node.properties ?? {};
  const lines = Object.keys(props).map((key) => {
    const pn = props[key];
    const opt = required.has(key) ? "" : "?";
    const desc = pn.description ? `  /** ${pn.description} */\n` : "";
    return `${desc}  readonly ${key}${opt}: ${tsType(pn, ctxFile)};`;
  });
  return `{\n${lines.join("\n")}\n}`;
}

function unionDefs(fileID) {
  const d = doc(fileID);
  return d.oneOf.map((item) => {
    const ref = item.$ref;
    const name = defName(ref);
    const def = resolveRef(ref, fileID);
    return { name, wireConst: def.properties.type.const };
  });
}

async function main() {
  for (const f of ["shared-types.json", "hello.json", "server-frames.json", "client-frames.json", "error-codes.json", "notice-kinds.json", "wire-names.json"]) {
    await load(f);
  }

  const b = [];
  b.push("// Code generated by contract/gen_ts.mjs from contract/schemas; DO NOT EDIT.");
  b.push("//");
  b.push("// Single-source WS contract for v2 (same source as internal/wscontract/types_gen.go).");
  b.push("// Regenerate with: node contract/gen_ts.mjs");
  b.push("");
  b.push("export type JsonValue = null | boolean | number | string | readonly JsonValue[] | { readonly [key: string]: JsonValue };");
  b.push("export type JsonObject = { readonly [key: string]: JsonValue };");
  b.push("");

  // Object defs -> interfaces; enum defs -> literal unions + const arrays.
  for (const fileID of ["shared-types.json", "hello.json", "error-codes.json", "notice-kinds.json", "server-frames.json", "client-frames.json"]) {
    const defs = doc(fileID).$defs ?? {};
    for (const name of Object.keys(defs).sort()) {
      const def = defs[name];
      if ("enum" in def) {
        b.push(`export type ${name} = ${def.enum.map((v) => JSON.stringify(v)).join(" | ")};`);
        b.push(`export const ${snakeUpper(name)}: readonly ${name}[] = [${def.enum.map((v) => JSON.stringify(v)).join(", ")}] as const;`);
        b.push("");
      } else if (def.type === "object" && !isOpaque(def)) {
        if (def.description) b.push(`/** ${def.description} */`);
        const required = new Set(def.required ?? []);
        const props = def.properties ?? {};
        b.push(`export interface ${name} {`);
        for (const key of Object.keys(props).sort()) {
          const pn = props[key];
          if (pn.description) b.push(`  /** ${pn.description} */`);
          const opt = required.has(key) ? "" : "?";
          b.push(`  readonly ${key}${opt}: ${tsType(pn, fileID)};`);
        }
        b.push("}");
        b.push("");
      }
    }
  }

  // Unions with an UnknownFrame passthrough (forward compatibility, R1).
  const server = unionDefs("server-frames.json");
  const client = unionDefs("client-frames.json");
  b.push("/** Any frame whose type is outside the closed union (dropped by the parser, never a parse failure). */");
  b.push("export interface UnknownFrame {");
  b.push("  readonly type: string;");
  b.push("  readonly [key: string]: unknown;");
  b.push("}");
  b.push("");
  b.push("export type ChatServerFrame =");
  b.push(server.map((d) => `  | ${d.name}`).join("\n"));
  b.push("  | UnknownFrame;");
  b.push("");
  b.push("export type ChatClientFrame =");
  b.push(client.map((d) => `  | ${d.name}`).join("\n"));
  b.push("  | UnknownFrame;");
  b.push("");

  b.push(`export const SERVER_FRAME_TYPES: readonly string[] = [${server.map((d) => JSON.stringify(d.wireConst)).join(", ")}] as const;`);
  b.push(`export const CLIENT_FRAME_TYPES: readonly string[] = [${client.map((d) => JSON.stringify(d.wireConst)).join(", ")}] as const;`);
  b.push("");
  b.push("/** Wire type of a decoded frame, or null when the payload is not an object. */");
  b.push("export function frameTypeOf(raw: unknown): string | null {");
  b.push("  if (typeof raw !== \"object\" || raw === null || Array.isArray(raw)) return null;");
  b.push("  const t = (raw as { type?: unknown }).type;");
  b.push("  return typeof t === \"string\" ? t : null;");
  b.push("}");
  b.push("");

  // Wire-name mapping (v2 FrameKind -> wire type), from wire-names.json.
  const wn = resolveRef("#/$defs/WireNames", "wire-names.json");
  const serverMap = wn.properties.server.properties;
  const clientMap = wn.properties.client.properties;
  b.push("/** v2 session FrameKind -> wire type emitted on the socket (owned by the bridge). */");
  b.push("export const FrameKindToWireName: Readonly<Record<string, string>> = Object.freeze({");
  for (const k of Object.keys(serverMap).sort()) b.push(`  ${JSON.stringify(k)}: ${JSON.stringify(serverMap[k].const)},`);
  b.push("});");
  b.push("");
  b.push("/** Client command names (identity mapping; v1 continuity). */");
  b.push("export const ClientWireNames: Readonly<Record<string, string>> = Object.freeze({");
  for (const k of Object.keys(clientMap).sort()) b.push(`  ${JSON.stringify(k)}: ${JSON.stringify(clientMap[k].const)},`);
  b.push("});");
  b.push("");

  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, b.join("\n"), "utf8");
  console.log(`gen_ts: wrote ${outPath}`);
}

function snakeUpper(name) {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
}

main().catch((err) => {
  console.error("gen_ts:", err);
  process.exit(1);
});
