// Generated by npm/platform/generate.mjs — do not edit by hand.
// Resolves to the absolute path of the prebuilt omo-webchat binary shipped in this package's exe/ directory.
'use strict';
const path = require('node:path');

module.exports = path.join(__dirname, 'exe', "omo-webchat-bin.exe");
