// Code generated by contract/gen_ts.mjs from contract/schemas; DO NOT EDIT.
//
// Single-source WS contract for v2 (same source as internal/wscontract/types_gen.go).
// Regenerate with: node contract/gen_ts.mjs

export type JsonValue = null | boolean | number | string | readonly JsonValue[] | { readonly [key: string]: JsonValue };
export type JsonObject = { readonly [key: string]: JsonValue };

export type ApprovalMethod = "select" | "confirm" | "input" | "editor";
export const APPROVAL_METHOD: readonly ApprovalMethod[] = ["select", "confirm", "input", "editor"] as const;

export interface AssistantDelta {
  readonly content?: string;
  readonly contentIndex?: number;
  readonly delta?: string;
  readonly kind: string;
  readonly partial?: JsonValue;
  readonly reason?: string;
}

export interface AssistantMessage {
  readonly blocks?: readonly ContentBlock[];
  readonly customType?: string;
  readonly model?: string;
  readonly role: string;
  readonly ts?: number;
  readonly usage?: JsonValue;
}

export interface ChatImage {
  readonly data: string;
  readonly mimeType: string;
}

export interface CommandEntry {
  readonly description?: string;
  readonly name: string;
  readonly source?: string;
  readonly sourceInfo?: CommandSourceInfo;
  readonly syntax?: string;
}

export interface CommandSourceInfo {
  readonly baseDir?: string;
  readonly origin?: string;
  readonly path?: string;
  readonly scope?: string;
  readonly source?: string;
}

export interface ContentBlock {
  readonly arguments?: JsonValue;
  readonly id?: string;
  readonly isError?: boolean;
  readonly kind: string;
  readonly name?: string;
  readonly text?: string;
  readonly thinking?: string;
}

export interface ContextUsage {
  readonly contextWindow: number;
  readonly percent: number;
  readonly tokens: number;
}

export interface ModelInfo {
  readonly input?: readonly string[];
  readonly modelId: string;
  readonly name?: string;
  readonly provider: string;
}

export interface ModelRef {
  readonly modelId: string;
  readonly provider: string;
}

export type NameOrigin = "auto" | "user" | "provider";
export const NAME_ORIGIN: readonly NameOrigin[] = ["auto", "user", "provider"] as const;

export interface ResumeCandidate {
  readonly hostPath?: string;
  readonly id: string;
  readonly name: string;
}

export type RunKind = "prompt" | "steer" | "follow_up";
export const RUN_KIND: readonly RunKind[] = ["prompt", "steer", "follow_up"] as const;

export interface ToolPayload {
  readonly content?: readonly {
  readonly text?: string;
}[];
  readonly details?: JsonValue;
}

export type ToolPhase = "start" | "update" | "end";
export const TOOL_PHASE: readonly ToolPhase[] = ["start", "update", "end"] as const;

export interface ClientHelloFrame {
  readonly type: "hello";
  /** Wire contract version the client expects */
  readonly version: number;
}

export interface HelloFrame {
  /** Human-readable server build identity */
  readonly serverVersion: string;
  readonly type: "hello";
  /** Wire contract version this server speaks */
  readonly version: number;
}

export type ErrorCode = "pi_eof" | "resume_failed" | "session_unloaded" | "session_mismatch" | "prompt_in_flight" | "compaction_in_flight" | "provider_error" | "persist_failed" | "decode_failed" | "bad_frame" | "unknown_type" | "bad_create" | "bad_provider" | "no_workspace" | "no_chat" | "start_failed";
export const ERROR_CODE: readonly ErrorCode[] = ["pi_eof", "resume_failed", "session_unloaded", "session_mismatch", "prompt_in_flight", "compaction_in_flight", "provider_error", "persist_failed", "decode_failed", "bad_frame", "unknown_type", "bad_create", "bad_provider", "no_workspace", "no_chat", "start_failed"] as const;

export type DurableNoticeKind = "retry_fallback_applied" | "retry_fallback_reverted" | "retry_fallback_succeeded" | "retry_fallback_exhausted" | "server_fallback_aborted" | "high_reasoning_warning";
export const DURABLE_NOTICE_KIND: readonly DurableNoticeKind[] = ["retry_fallback_applied", "retry_fallback_reverted", "retry_fallback_succeeded", "retry_fallback_exhausted", "server_fallback_aborted", "high_reasoning_warning"] as const;

export interface AckFrame {
  readonly command: string;
  readonly id?: string;
  /** Correlates with the client request (invariant 19) */
  readonly requestId?: string;
  readonly sessionId?: string;
  readonly type: "ack";
}

export interface ApprovalFrame {
  readonly id: string;
  readonly message?: string;
  readonly method: ApprovalMethod;
  readonly options?: readonly string[];
  readonly placeholder?: string;
  readonly prefill?: string;
  readonly sessionId: string;
  readonly timeout?: number;
  readonly title?: string;
  readonly type: "approval";
}

export interface ChatNameFrame {
  readonly name: string;
  readonly origin: NameOrigin;
  readonly sessionId: string;
  readonly type: "chat.name";
}

export interface CommandsFrame {
  readonly commands: readonly CommandEntry[];
  readonly sessionId: string;
  readonly type: "commands";
}

export interface CompactionDoneFrame {
  readonly error?: string;
  readonly sessionId: string;
  readonly type: "compaction.done";
}

export interface CompactionStartedFrame {
  readonly sessionId: string;
  readonly type: "compaction.started";
}

export interface ControlResultFrame {
  readonly command: string;
  readonly message?: string;
  readonly requestId?: string;
  readonly sessionId: string;
  readonly success: boolean;
  readonly type: "control.result";
}

export interface EntriesFrame {
  /** History entries; bounds per invariant 18 (100 entries / 256 KiB per page) */
  readonly entries: readonly JsonValue[];
  /** REQUIRED on every entries frame (invariant 18) */
  readonly final: boolean;
  /** Present only on the terminal page */
  readonly leafId?: string;
  readonly sessionId: string;
  readonly type: "entries";
}

export interface ErrorFrame {
  /** resume_failed only: scanned branch candidates */
  readonly candidates?: readonly ResumeCandidate[];
  readonly code?: ErrorCode;
  /** FailedRpcCommand — provider command string, open on purpose */
  readonly command?: string;
  /** resume_failed only: stored identity path no longer exists */
  readonly dangling?: boolean;
  readonly message: string;
  readonly requestId?: string;
  readonly sessionId?: string;
  readonly type: "error";
}

export interface ExtensionEventFrame {
  readonly data?: JsonValue;
  readonly name: string;
  readonly sessionId: string;
  readonly type: "extensionEvent";
}

export interface MessageDeltaFrame {
  readonly delta: AssistantDelta;
  readonly messageId?: string;
  readonly sessionId: string;
  readonly type: "messageDelta";
}

export interface MessageFrame {
  readonly message: AssistantMessage;
  readonly sessionId: string;
  readonly type: "message";
}

export interface ModelsFrame {
  readonly models: readonly ModelInfo[];
  readonly sessionId: string;
  readonly type: "models";
}

export interface NoticeFrame {
  /** RFC3339Nano receipt time; every notice carries one (invariant 14) */
  readonly at: string;
  /** Open set: durable kinds are enumerated in notice-kinds.json; everything else is transient */
  readonly kind: string;
  /** Server-assigned replay identity for durable notices */
  readonly nid?: string;
  readonly payload?: JsonValue;
  readonly sessionId: string;
  readonly type: "notice";
}

export interface PongFrame {
  readonly sessionId?: string;
  readonly type: "pong";
}

export interface ReadyFrame {
  readonly piSessionId: string | null;
  readonly resumed: boolean;
  readonly sessionId: string;
  readonly type: "ready";
}

export interface RunDoneFrame {
  readonly reason: string;
  readonly sessionId: string;
  readonly type: "run.done";
}

export interface RunStartedFrame {
  readonly sessionId: string;
  readonly type: "run.started";
}

export interface StateFrame {
  readonly isCompacting: boolean;
  readonly isStreaming: boolean;
  readonly model?: ModelRef | null;
  readonly sessionId: string;
  readonly sessionName?: string;
  readonly thinkingLevel?: string;
  readonly type: "state";
}

export interface StatsFrame {
  readonly contextUsage?: ContextUsage;
  readonly cost?: number;
  readonly sessionId: string;
  readonly tokens?: JsonValue;
  readonly type: "stats";
}

export interface ToolFrame {
  readonly args?: JsonValue;
  readonly isError?: boolean;
  readonly partial?: ToolPayload;
  readonly phase: ToolPhase;
  readonly result?: ToolPayload;
  readonly sessionId: string;
  readonly toolCallId: string;
  readonly toolName: string;
  readonly type: "tool";
}

export interface ActivityRefreshFrame {
  readonly sessionId: string;
  readonly type: "activity.refresh";
}

export interface ApprovalRespondFrame {
  readonly cancelled?: boolean;
  readonly confirmed?: boolean;
  readonly id: string;
  readonly requestId?: string;
  readonly sessionId: string;
  readonly type: "approval.respond";
  readonly value?: string;
}

export interface ChatAbortFrame {
  readonly sessionId: string;
  readonly type: "chat.abort";
}

export interface ChatCloseFrame {
  readonly sessionId: string;
  readonly type: "chat.close";
}

export interface ChatCommandsFrame {
  readonly sessionId: string;
  readonly type: "chat.commands";
}

export interface ChatCompactFrame {
  readonly sessionId: string;
  readonly type: "chat.compact";
}

export interface ChatCreateFrame {
  readonly chatId: string;
  readonly type: "chat.create";
  readonly wsId: string;
}

export interface ChatDisconnectFrame {
  readonly sessionId: string;
  readonly type: "chat.disconnect";
}

export interface ChatModelsFrame {
  readonly sessionId: string;
  readonly type: "chat.models";
}

export interface ChatResumeFrame {
  readonly sessionId: string;
  readonly since?: string;
  readonly type: "chat.resume";
}

export interface ChatSendFrame {
  readonly run: {
  readonly kind: RunKind;
  readonly message: string;
  readonly images?: readonly ChatImage[];
};
  readonly sessionId: string;
  readonly type: "chat.send";
}

export interface ChatSetFrame {
  readonly model?: ModelRef;
  readonly requestId?: string;
  readonly sessionId: string;
  readonly thinkingLevel?: string;
  readonly type: "chat.set";
}

export interface ChatStatsFrame {
  readonly sessionId: string;
  readonly type: "chat.stats";
}

export interface PingFrame {
  readonly type: "ping";
}

/** Any frame whose type is outside the closed union (dropped by the parser, never a parse failure). */
export interface UnknownFrame {
  readonly type: string;
  readonly [key: string]: unknown;
}

export type ChatServerFrame =
  | ReadyFrame
  | ChatNameFrame
  | MessageDeltaFrame
  | MessageFrame
  | ToolFrame
  | StateFrame
  | StatsFrame
  | ExtensionEventFrame
  | ApprovalFrame
  | CommandsFrame
  | ModelsFrame
  | EntriesFrame
  | CompactionStartedFrame
  | CompactionDoneFrame
  | RunStartedFrame
  | RunDoneFrame
  | AckFrame
  | ControlResultFrame
  | ErrorFrame
  | NoticeFrame
  | PongFrame
  | HelloFrame
  | UnknownFrame;

export type ChatClientFrame =
  | PingFrame
  | ChatCreateFrame
  | ChatSendFrame
  | ChatAbortFrame
  | ChatSetFrame
  | ApprovalRespondFrame
  | ChatCommandsFrame
  | ChatCompactFrame
  | ChatModelsFrame
  | ChatStatsFrame
  | ActivityRefreshFrame
  | ChatResumeFrame
  | ChatCloseFrame
  | ChatDisconnectFrame
  | ClientHelloFrame
  | UnknownFrame;

export const SERVER_FRAME_TYPES: readonly string[] = ["ready", "chat.name", "messageDelta", "message", "tool", "state", "stats", "extensionEvent", "approval", "commands", "models", "entries", "compaction.started", "compaction.done", "run.started", "run.done", "ack", "control.result", "error", "notice", "pong", "hello"] as const;
export const CLIENT_FRAME_TYPES: readonly string[] = ["ping", "chat.create", "chat.send", "chat.abort", "chat.set", "approval.respond", "chat.commands", "chat.compact", "chat.models", "chat.stats", "activity.refresh", "chat.resume", "chat.close", "chat.disconnect", "hello"] as const;

/** Wire type of a decoded frame, or null when the payload is not an object. */
export function frameTypeOf(raw: unknown): string | null {
  if (typeof raw !== "object" || raw === null || Array.isArray(raw)) return null;
  const t = (raw as { type?: unknown }).type;
  return typeof t === "string" ? t : null;
}

/** v2 session FrameKind -> wire type emitted on the socket (owned by the bridge). */
export const FrameKindToWireName: Readonly<Record<string, string>> = Object.freeze({
  "ack": "ack",
  "approval": "approval",
  "commands": "commands",
  "compaction.done": "compaction.done",
  "compaction.started": "compaction.started",
  "control.result": "control.result",
  "entries": "entries",
  "error": "error",
  "extensionEvent": "extensionEvent",
  "message": "message",
  "message.delta": "messageDelta",
  "models": "models",
  "name": "chat.name",
  "notice": "notice",
  "ready": "ready",
  "run.done": "run.done",
  "run.started": "run.started",
  "state": "state",
  "stats": "stats",
  "tool": "tool",
});

/** Client command names (identity mapping; v1 continuity). */
export const ClientWireNames: Readonly<Record<string, string>> = Object.freeze({
  "activity.refresh": "activity.refresh",
  "approval.respond": "approval.respond",
  "chat.abort": "chat.abort",
  "chat.close": "chat.close",
  "chat.commands": "chat.commands",
  "chat.compact": "chat.compact",
  "chat.create": "chat.create",
  "chat.disconnect": "chat.disconnect",
  "chat.models": "chat.models",
  "chat.resume": "chat.resume",
  "chat.send": "chat.send",
  "chat.set": "chat.set",
  "chat.stats": "chat.stats",
  "ping": "ping",
});
